package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Accmaster generated by hbm2java
 */
@Entity
@Table(name="accmaster"
    ,catalog="e2rp"
)
public class Accmaster  implements java.io.Serializable {


     private Integer accId;
     private String accName;
     private String accType;
     private int accParentid;
     private Date accCreateddt;
     private int accCreatedby;
     private String accIsdeleteable;

    public Accmaster() {
    }

	
    public Accmaster(String accName, int accParentid, Date accCreateddt, int accCreatedby, String accIsdeleteable) {
        this.accName = accName;
        this.accParentid = accParentid;
        this.accCreateddt = accCreateddt;
        this.accCreatedby = accCreatedby;
        this.accIsdeleteable = accIsdeleteable;
    }
    public Accmaster(String accName, String accType, int accParentid, Date accCreateddt, int accCreatedby, String accIsdeleteable) {
       this.accName = accName;
       this.accType = accType;
       this.accParentid = accParentid;
       this.accCreateddt = accCreateddt;
       this.accCreatedby = accCreatedby;
       this.accIsdeleteable = accIsdeleteable;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ACC_ID", unique=true, nullable=false)
    public Integer getAccId() {
        return this.accId;
    }
    
    public void setAccId(Integer accId) {
        this.accId = accId;
    }

    
    @Column(name="ACC_NAME", nullable=false, length=100)
    public String getAccName() {
        return this.accName;
    }
    
    public void setAccName(String accName) {
        this.accName = accName;
    }

    
    @Column(name="ACC_TYPE", length=50)
    public String getAccType() {
        return this.accType;
    }
    
    public void setAccType(String accType) {
        this.accType = accType;
    }

    
    @Column(name="ACC_PARENTID", nullable=false)
    public int getAccParentid() {
        return this.accParentid;
    }
    
    public void setAccParentid(int accParentid) {
        this.accParentid = accParentid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACC_CREATEDDT", nullable=false, length=19)
    public Date getAccCreateddt() {
        return this.accCreateddt;
    }
    
    public void setAccCreateddt(Date accCreateddt) {
        this.accCreateddt = accCreateddt;
    }

    
    @Column(name="ACC_CREATEDBY", nullable=false)
    public int getAccCreatedby() {
        return this.accCreatedby;
    }
    
    public void setAccCreatedby(int accCreatedby) {
        this.accCreatedby = accCreatedby;
    }

    
    @Column(name="ACC_ISDELETEABLE", nullable=false, length=5)
    public String getAccIsdeleteable() {
        return this.accIsdeleteable;
    }
    
    public void setAccIsdeleteable(String accIsdeleteable) {
        this.accIsdeleteable = accIsdeleteable;
    }




}


