package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Accmasterdetail generated by hbm2java
 */
@Entity
@Table(name="accmasterdetail"
    ,catalog="e2rp"
)
public class Accmasterdetail  implements java.io.Serializable {


     private AccmasterdetailId id;
     private String accName;
     private String accAddress;
     private String accPhoneno;
     private String accEmail;
     private BigDecimal accOpbalance;
     private String accRemarks;

    public Accmasterdetail() {
    }

	
    public Accmasterdetail(AccmasterdetailId id) {
        this.id = id;
    }
    public Accmasterdetail(AccmasterdetailId id, String accName, String accAddress, String accPhoneno, String accEmail, BigDecimal accOpbalance, String accRemarks) {
       this.id = id;
       this.accName = accName;
       this.accAddress = accAddress;
       this.accPhoneno = accPhoneno;
       this.accEmail = accEmail;
       this.accOpbalance = accOpbalance;
       this.accRemarks = accRemarks;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="accDtlid", column=@Column(name="ACC_DTLID", nullable=false) ), 
        @AttributeOverride(name="accId", column=@Column(name="ACC_ID", nullable=false) ) } )
    public AccmasterdetailId getId() {
        return this.id;
    }
    
    public void setId(AccmasterdetailId id) {
        this.id = id;
    }

    
    @Column(name="ACC_NAME", length=50)
    public String getAccName() {
        return this.accName;
    }
    
    public void setAccName(String accName) {
        this.accName = accName;
    }

    
    @Column(name="ACC_ADDRESS")
    public String getAccAddress() {
        return this.accAddress;
    }
    
    public void setAccAddress(String accAddress) {
        this.accAddress = accAddress;
    }

    
    @Column(name="ACC_PHONENO", length=20)
    public String getAccPhoneno() {
        return this.accPhoneno;
    }
    
    public void setAccPhoneno(String accPhoneno) {
        this.accPhoneno = accPhoneno;
    }

    
    @Column(name="ACC_EMAIL", length=100)
    public String getAccEmail() {
        return this.accEmail;
    }
    
    public void setAccEmail(String accEmail) {
        this.accEmail = accEmail;
    }

    
    @Column(name="ACC_OPBALANCE", precision=18)
    public BigDecimal getAccOpbalance() {
        return this.accOpbalance;
    }
    
    public void setAccOpbalance(BigDecimal accOpbalance) {
        this.accOpbalance = accOpbalance;
    }

    
    @Column(name="ACC_REMARKS", length=250)
    public String getAccRemarks() {
        return this.accRemarks;
    }
    
    public void setAccRemarks(String accRemarks) {
        this.accRemarks = accRemarks;
    }




}


