package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccmasterdetailId generated by hbm2java
 */
@Embeddable
public class AccmasterdetailId  implements java.io.Serializable {


     private int accDtlid;
     private int accId;

    public AccmasterdetailId() {
    }

    public AccmasterdetailId(int accDtlid, int accId) {
       this.accDtlid = accDtlid;
       this.accId = accId;
    }
   


    @Column(name="ACC_DTLID", nullable=false)
    public int getAccDtlid() {
        return this.accDtlid;
    }
    
    public void setAccDtlid(int accDtlid) {
        this.accDtlid = accDtlid;
    }


    @Column(name="ACC_ID", nullable=false)
    public int getAccId() {
        return this.accId;
    }
    
    public void setAccId(int accId) {
        this.accId = accId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AccmasterdetailId) ) return false;
		 AccmasterdetailId castOther = ( AccmasterdetailId ) other; 
         
		 return (this.getAccDtlid()==castOther.getAccDtlid())
 && (this.getAccId()==castOther.getAccId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAccDtlid();
         result = 37 * result + this.getAccId();
         return result;
   }   


}


