package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="e2rp"
)
public class Account  implements java.io.Serializable {


     private Integer accId;
     private String accCOrSCode;
     private String accType;
     private BigDecimal accDueamount;
     private String accChequeno;
     private Date accChequedt;
     private BigDecimal accPaidamot;
     private String accPaymenttype;
     private String accOtherinfo;
     private Date accDate;
     private Set<Accmasterdetail> accmasterdetails = new HashSet<Accmasterdetail>(0);

    public Account() {
    }

	
    public Account(String accCOrSCode, String accType, BigDecimal accDueamount, BigDecimal accPaidamot, Date accDate) {
        this.accCOrSCode = accCOrSCode;
        this.accType = accType;
        this.accDueamount = accDueamount;
        this.accPaidamot = accPaidamot;
        this.accDate = accDate;
    }
    public Account(String accCOrSCode, String accType, BigDecimal accDueamount, String accChequeno, Date accChequedt, BigDecimal accPaidamot, String accPaymenttype, String accOtherinfo, Date accDate, Set<Accmasterdetail> accmasterdetails) {
       this.accCOrSCode = accCOrSCode;
       this.accType = accType;
       this.accDueamount = accDueamount;
       this.accChequeno = accChequeno;
       this.accChequedt = accChequedt;
       this.accPaidamot = accPaidamot;
       this.accPaymenttype = accPaymenttype;
       this.accOtherinfo = accOtherinfo;
       this.accDate = accDate;
       this.accmasterdetails = accmasterdetails;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ACC_ID", unique=true, nullable=false)
    public Integer getAccId() {
        return this.accId;
    }
    
    public void setAccId(Integer accId) {
        this.accId = accId;
    }

    
    @Column(name="ACC_C_OR_S_CODE", nullable=false, length=50)
    public String getAccCOrSCode() {
        return this.accCOrSCode;
    }
    
    public void setAccCOrSCode(String accCOrSCode) {
        this.accCOrSCode = accCOrSCode;
    }

    
    @Column(name="ACC_TYPE", nullable=false, length=50)
    public String getAccType() {
        return this.accType;
    }
    
    public void setAccType(String accType) {
        this.accType = accType;
    }

    
    @Column(name="ACC_DUEAMOUNT", nullable=false, precision=18)
    public BigDecimal getAccDueamount() {
        return this.accDueamount;
    }
    
    public void setAccDueamount(BigDecimal accDueamount) {
        this.accDueamount = accDueamount;
    }

    
    @Column(name="ACC_CHEQUENO", length=15)
    public String getAccChequeno() {
        return this.accChequeno;
    }
    
    public void setAccChequeno(String accChequeno) {
        this.accChequeno = accChequeno;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACC_CHEQUEDT", length=19)
    public Date getAccChequedt() {
        return this.accChequedt;
    }
    
    public void setAccChequedt(Date accChequedt) {
        this.accChequedt = accChequedt;
    }

    
    @Column(name="ACC_PAIDAMOT", nullable=false, precision=18)
    public BigDecimal getAccPaidamot() {
        return this.accPaidamot;
    }
    
    public void setAccPaidamot(BigDecimal accPaidamot) {
        this.accPaidamot = accPaidamot;
    }

    
    @Column(name="ACC_PAYMENTTYPE", length=10)
    public String getAccPaymenttype() {
        return this.accPaymenttype;
    }
    
    public void setAccPaymenttype(String accPaymenttype) {
        this.accPaymenttype = accPaymenttype;
    }

    
    @Column(name="ACC_OTHERINFO", length=600)
    public String getAccOtherinfo() {
        return this.accOtherinfo;
    }
    
    public void setAccOtherinfo(String accOtherinfo) {
        this.accOtherinfo = accOtherinfo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ACC_DATE", nullable=false, length=19)
    public Date getAccDate() {
        return this.accDate;
    }
    
    public void setAccDate(Date accDate) {
        this.accDate = accDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<Accmasterdetail> getAccmasterdetails() {
        return this.accmasterdetails;
    }
    
    public void setAccmasterdetails(Set<Accmasterdetail> accmasterdetails) {
        this.accmasterdetails = accmasterdetails;
    }




}


