package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetsTable generated by hbm2java
 */
@Entity
@Table(name="assets_table"
    ,catalog="e2rp"
)
public class AssetsTable  implements java.io.Serializable {


     private Integer assId;
     private Date assDate;
     private String assParticulars;
     private String assAmo;

    public AssetsTable() {
    }

    public AssetsTable(Date assDate, String assParticulars, String assAmo) {
       this.assDate = assDate;
       this.assParticulars = assParticulars;
       this.assAmo = assAmo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Ass_ID", unique=true, nullable=false)
    public Integer getAssId() {
        return this.assId;
    }
    
    public void setAssId(Integer assId) {
        this.assId = assId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ASS_DATE", length=10)
    public Date getAssDate() {
        return this.assDate;
    }
    
    public void setAssDate(Date assDate) {
        this.assDate = assDate;
    }

    
    @Column(name="ASS_PARTICULARS", length=2500)
    public String getAssParticulars() {
        return this.assParticulars;
    }
    
    public void setAssParticulars(String assParticulars) {
        this.assParticulars = assParticulars;
    }

    
    @Column(name="ASS_AMO", length=50)
    public String getAssAmo() {
        return this.assAmo;
    }
    
    public void setAssAmo(String assAmo) {
        this.assAmo = assAmo;
    }




}


