package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookIssuemaster generated by hbm2java
 */
@Entity
@Table(name="book_issuemaster"
    ,catalog="e2rp"
)
public class BookIssuemaster  implements java.io.Serializable {


     private Integer issueId;
     private int bookId;
     private int memberId;
     private Date issueDate;
     private Date dueDate;
     private String isIssued;

    public BookIssuemaster() {
    }

    public BookIssuemaster(int bookId, int memberId, Date issueDate, Date dueDate, String isIssued) {
       this.bookId = bookId;
       this.memberId = memberId;
       this.issueDate = issueDate;
       this.dueDate = dueDate;
       this.isIssued = isIssued;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ISSUE_ID", unique=true, nullable=false)
    public Integer getIssueId() {
        return this.issueId;
    }
    
    public void setIssueId(Integer issueId) {
        this.issueId = issueId;
    }

    
    @Column(name="BOOK_ID", nullable=false)
    public int getBookId() {
        return this.bookId;
    }
    
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    
    @Column(name="MEMBER_ID", nullable=false)
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ISSUE_DATE", nullable=false, length=19)
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DUE_DATE", nullable=false, length=19)
    public Date getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    
    @Column(name="IS_ISSUED", nullable=false, length=20)
    public String getIsIssued() {
        return this.isIssued;
    }
    
    public void setIsIssued(String isIssued) {
        this.isIssued = isIssued;
    }




}


