package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bookmaster generated by hbm2java
 */
@Entity
@Table(name="bookmaster"
    ,catalog="e2rp"
)
public class Bookmaster  implements java.io.Serializable {


     private Integer bookId;
     private int bookSubId;
     private String bookTitle;
     private String bookAuthor;
     private String bookPublisher;
     private String bookIsbn;
     private String bookRackNo;
     private BigDecimal bookPrice;
     private Date bookPurDate;
     private String bookVolume;
     private int bookCreatedby;
     private Date bookCreateddt;
     private String bookIsactive;

    public Bookmaster() {
    }

    public Bookmaster(int bookSubId, String bookTitle, String bookAuthor, String bookPublisher, String bookIsbn, String bookRackNo, BigDecimal bookPrice, Date bookPurDate, String bookVolume, int bookCreatedby, Date bookCreateddt, String bookIsactive) {
       this.bookSubId = bookSubId;
       this.bookTitle = bookTitle;
       this.bookAuthor = bookAuthor;
       this.bookPublisher = bookPublisher;
       this.bookIsbn = bookIsbn;
       this.bookRackNo = bookRackNo;
       this.bookPrice = bookPrice;
       this.bookPurDate = bookPurDate;
       this.bookVolume = bookVolume;
       this.bookCreatedby = bookCreatedby;
       this.bookCreateddt = bookCreateddt;
       this.bookIsactive = bookIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BOOK_ID", unique=true, nullable=false)
    public Integer getBookId() {
        return this.bookId;
    }
    
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    
    @Column(name="BOOK_SUB_ID", nullable=false)
    public int getBookSubId() {
        return this.bookSubId;
    }
    
    public void setBookSubId(int bookSubId) {
        this.bookSubId = bookSubId;
    }

    
    @Column(name="BOOK_TITLE", nullable=false, length=100)
    public String getBookTitle() {
        return this.bookTitle;
    }
    
    public void setBookTitle(String bookTitle) {
        this.bookTitle = bookTitle;
    }

    
    @Column(name="BOOK_AUTHOR", nullable=false, length=50)
    public String getBookAuthor() {
        return this.bookAuthor;
    }
    
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor;
    }

    
    @Column(name="BOOK_PUBLISHER", nullable=false, length=50)
    public String getBookPublisher() {
        return this.bookPublisher;
    }
    
    public void setBookPublisher(String bookPublisher) {
        this.bookPublisher = bookPublisher;
    }

    
    @Column(name="BOOK_ISBN", nullable=false, length=50)
    public String getBookIsbn() {
        return this.bookIsbn;
    }
    
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn;
    }

    
    @Column(name="BOOK_RACK_NO", nullable=false, length=25)
    public String getBookRackNo() {
        return this.bookRackNo;
    }
    
    public void setBookRackNo(String bookRackNo) {
        this.bookRackNo = bookRackNo;
    }

    
    @Column(name="BOOK_PRICE", nullable=false, precision=18)
    public BigDecimal getBookPrice() {
        return this.bookPrice;
    }
    
    public void setBookPrice(BigDecimal bookPrice) {
        this.bookPrice = bookPrice;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BOOK_PUR_DATE", nullable=false, length=19)
    public Date getBookPurDate() {
        return this.bookPurDate;
    }
    
    public void setBookPurDate(Date bookPurDate) {
        this.bookPurDate = bookPurDate;
    }

    
    @Column(name="BOOK_VOLUME", nullable=false, length=10)
    public String getBookVolume() {
        return this.bookVolume;
    }
    
    public void setBookVolume(String bookVolume) {
        this.bookVolume = bookVolume;
    }

    
    @Column(name="BOOK_CREATEDBY", nullable=false)
    public int getBookCreatedby() {
        return this.bookCreatedby;
    }
    
    public void setBookCreatedby(int bookCreatedby) {
        this.bookCreatedby = bookCreatedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="BOOK_CREATEDDT", nullable=false, length=19)
    public Date getBookCreateddt() {
        return this.bookCreateddt;
    }
    
    public void setBookCreateddt(Date bookCreateddt) {
        this.bookCreateddt = bookCreateddt;
    }

    
    @Column(name="BOOK_ISACTIVE", nullable=false, length=1)
    public String getBookIsactive() {
        return this.bookIsactive;
    }
    
    public void setBookIsactive(String bookIsactive) {
        this.bookIsactive = bookIsactive;
    }




}


