package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BookReturn generated by hbm2java
 */
@Entity
@Table(name="book_return"
    ,catalog="e2rp"
)
public class BookReturn  implements java.io.Serializable {


     private Integer returnId;
     private int bookId;
     private int memberId;
     private Date returnDate;
     private BigDecimal fine;

    public BookReturn() {
    }

    public BookReturn(int bookId, int memberId, Date returnDate, BigDecimal fine) {
       this.bookId = bookId;
       this.memberId = memberId;
       this.returnDate = returnDate;
       this.fine = fine;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RETURN_ID", unique=true, nullable=false)
    public Integer getReturnId() {
        return this.returnId;
    }
    
    public void setReturnId(Integer returnId) {
        this.returnId = returnId;
    }

    
    @Column(name="BOOK_ID", nullable=false)
    public int getBookId() {
        return this.bookId;
    }
    
    public void setBookId(int bookId) {
        this.bookId = bookId;
    }

    
    @Column(name="MEMBER_ID", nullable=false)
    public int getMemberId() {
        return this.memberId;
    }
    
    public void setMemberId(int memberId) {
        this.memberId = memberId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RETURN_DATE", nullable=false, length=19)
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    
    @Column(name="FINE", nullable=false, precision=18)
    public BigDecimal getFine() {
        return this.fine;
    }
    
    public void setFine(BigDecimal fine) {
        this.fine = fine;
    }




}


