package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BuildingMaster generated by hbm2java
 */
@Entity
@Table(name="building_master"
    ,catalog="e2rp"
)
public class BuildingMaster  implements java.io.Serializable {


     private Integer buildingId;
     private String buildingName;
     private int landId;
     private String flag1;
     private String flag2;
     private String flag3;
     private String buildingIsactive;

    public BuildingMaster() {
    }

    public BuildingMaster(String buildingName, int landId, String flag1, String flag2, String flag3, String buildingIsactive) {
       this.buildingName = buildingName;
       this.landId = landId;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.buildingIsactive = buildingIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="BUILDING_ID", unique=true, nullable=false)
    public Integer getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(Integer buildingId) {
        this.buildingId = buildingId;
    }

    
    @Column(name="BUILDING_NAME", nullable=false, length=50)
    public String getBuildingName() {
        return this.buildingName;
    }
    
    public void setBuildingName(String buildingName) {
        this.buildingName = buildingName;
    }

    
    @Column(name="LAND_ID", nullable=false)
    public int getLandId() {
        return this.landId;
    }
    
    public void setLandId(int landId) {
        this.landId = landId;
    }

    
    @Column(name="FLAG_1", nullable=false, length=50)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", nullable=false, length=50)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", nullable=false, length=50)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="BUILDING_ISACTIVE", nullable=false, length=10)
    public String getBuildingIsactive() {
        return this.buildingIsactive;
    }
    
    public void setBuildingIsactive(String buildingIsactive) {
        this.buildingIsactive = buildingIsactive;
    }




}


