package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClassMaster generated by hbm2java
 */
@Entity
@Table(name="class_master"
    ,catalog="e2rp"
)
public class ClassMaster  implements java.io.Serializable {


     private Integer classId;
     private String className;
     private String classIsactive;
     

    public ClassMaster() {
    }

	
    public ClassMaster(String className, String classIsactive) {
        this.className = className;
        this.classIsactive = classIsactive;
    }
    
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CLASS_ID", unique=true, nullable=false)
    public Integer getClassId() {
        return this.classId;
    }
    
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    
    @Column(name="CLASS_NAME", nullable=false, length=10)
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

    
    @Column(name="CLASS_ISACTIVE", nullable=false, length=10)
    public String getClassIsactive() {
        return this.classIsactive;
    }
    
    public void setClassIsactive(String classIsactive) {
        this.classIsactive = classIsactive;
    }






}


