package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Contradetails generated by hbm2java
 */
@Entity
@Table(name="contradetails"
    ,catalog="e2rp"
)
public class Contradetails  implements java.io.Serializable {


     private ContradetailsId id;
     private String conByorto;
     private String conNature;
     private String conParticulars;
     private int conAccId;
     private BigDecimal conDramount;
     private BigDecimal conCramount;

    public Contradetails() {
    }

	
    public Contradetails(ContradetailsId id, String conByorto, String conNature, String conParticulars, int conAccId) {
        this.id = id;
        this.conByorto = conByorto;
        this.conNature = conNature;
        this.conParticulars = conParticulars;
        this.conAccId = conAccId;
    }
    public Contradetails(ContradetailsId id, String conByorto, String conNature, String conParticulars, int conAccId, BigDecimal conDramount, BigDecimal conCramount) {
       this.id = id;
       this.conByorto = conByorto;
       this.conNature = conNature;
       this.conParticulars = conParticulars;
       this.conAccId = conAccId;
       this.conDramount = conDramount;
       this.conCramount = conCramount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="conDtlid", column=@Column(name="CON_DTLID", nullable=false) ), 
        @AttributeOverride(name="conId", column=@Column(name="CON_ID", nullable=false) ) } )
    public ContradetailsId getId() {
        return this.id;
    }
    
    public void setId(ContradetailsId id) {
        this.id = id;
    }

    
    @Column(name="CON_BYORTO", nullable=false, length=20)
    public String getConByorto() {
        return this.conByorto;
    }
    
    public void setConByorto(String conByorto) {
        this.conByorto = conByorto;
    }

    
    @Column(name="CON_NATURE", nullable=false, length=50)
    public String getConNature() {
        return this.conNature;
    }
    
    public void setConNature(String conNature) {
        this.conNature = conNature;
    }

    
    @Column(name="CON_PARTICULARS", nullable=false, length=50)
    public String getConParticulars() {
        return this.conParticulars;
    }
    
    public void setConParticulars(String conParticulars) {
        this.conParticulars = conParticulars;
    }

    
    @Column(name="CON_ACC_ID", nullable=false)
    public int getConAccId() {
        return this.conAccId;
    }
    
    public void setConAccId(int conAccId) {
        this.conAccId = conAccId;
    }

    
    @Column(name="CON_DRAMOUNT", precision=18)
    public BigDecimal getConDramount() {
        return this.conDramount;
    }
    
    public void setConDramount(BigDecimal conDramount) {
        this.conDramount = conDramount;
    }

    
    @Column(name="CON_CRAMOUNT", precision=18)
    public BigDecimal getConCramount() {
        return this.conCramount;
    }
    
    public void setConCramount(BigDecimal conCramount) {
        this.conCramount = conCramount;
    }




}


