package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ContactUs generated by hbm2java
 */
@Entity
@Table(name="contact_us"
    ,catalog="e2rp"
)
public class ContactUs  implements java.io.Serializable {


     private Integer serialId;
     private String contactName;
     private String contactEmail;
     private String contactPhone;
     private String contactMessege;
     private String createdOn;
     private String contactUsIsactive;

    public ContactUs() {
    }

	
    public ContactUs(String contactName, String createdOn, String contactUsIsactive) {
        this.contactName = contactName;
        this.createdOn = createdOn;
        this.contactUsIsactive = contactUsIsactive;
    }
    public ContactUs(String contactName, String contactEmail, String contactPhone, String contactMessege, String createdOn, String contactUsIsactive) {
       this.contactName = contactName;
       this.contactEmail = contactEmail;
       this.contactPhone = contactPhone;
       this.contactMessege = contactMessege;
       this.createdOn = createdOn;
       this.contactUsIsactive = contactUsIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SERIAL_ID", unique=true, nullable=false)
    public Integer getSerialId() {
        return this.serialId;
    }
    
    public void setSerialId(Integer serialId) {
        this.serialId = serialId;
    }

    
    @Column(name="CONTACT_NAME", nullable=false, length=50)
    public String getContactName() {
        return this.contactName;
    }
    
    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    
    @Column(name="CONTACT_EMAIL", length=50)
    public String getContactEmail() {
        return this.contactEmail;
    }
    
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail;
    }

    
    @Column(name="CONTACT_PHONE", length=50)
    public String getContactPhone() {
        return this.contactPhone;
    }
    
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    
    @Column(name="CONTACT_MESSEGE", length=50)
    public String getContactMessege() {
        return this.contactMessege;
    }
    
    public void setContactMessege(String contactMessege) {
        this.contactMessege = contactMessege;
    }

    
    @Column(name="CREATED_ON", nullable=false, length=50)
    public String getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(String createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="CONTACT_US_ISACTIVE", nullable=false, length=50)
    public String getContactUsIsactive() {
        return this.contactUsIsactive;
    }
    
    public void setContactUsIsactive(String contactUsIsactive) {
        this.contactUsIsactive = contactUsIsactive;
    }




}


