package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contramaster generated by hbm2java
 */
@Entity
@Table(name="contramaster"
    ,catalog="e2rp"
)
public class Contramaster  implements java.io.Serializable {


     private Integer conId;
     private int conCodeid;
     private String conCode;
     private int conTocid;
     private Date conVoudate;
     private String conNarration;
     private String conType;
     private Integer conChqno;
     private String conChqdate;

    public Contramaster() {
    }

	
    public Contramaster(int conCodeid, String conCode, int conTocid, Date conVoudate, String conNarration, String conType) {
        this.conCodeid = conCodeid;
        this.conCode = conCode;
        this.conTocid = conTocid;
        this.conVoudate = conVoudate;
        this.conNarration = conNarration;
        this.conType = conType;
    }
    public Contramaster(int conCodeid, String conCode, int conTocid, Date conVoudate, String conNarration, String conType, Integer conChqno, String conChqdate) {
       this.conCodeid = conCodeid;
       this.conCode = conCode;
       this.conTocid = conTocid;
       this.conVoudate = conVoudate;
       this.conNarration = conNarration;
       this.conType = conType;
       this.conChqno = conChqno;
       this.conChqdate = conChqdate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CON_ID", unique=true, nullable=false)
    public Integer getConId() {
        return this.conId;
    }
    
    public void setConId(Integer conId) {
        this.conId = conId;
    }

    
    @Column(name="CON_CODEID", nullable=false)
    public int getConCodeid() {
        return this.conCodeid;
    }
    
    public void setConCodeid(int conCodeid) {
        this.conCodeid = conCodeid;
    }

    
    @Column(name="CON_CODE", nullable=false, length=20)
    public String getConCode() {
        return this.conCode;
    }
    
    public void setConCode(String conCode) {
        this.conCode = conCode;
    }

    
    @Column(name="CON_TOCID", nullable=false)
    public int getConTocid() {
        return this.conTocid;
    }
    
    public void setConTocid(int conTocid) {
        this.conTocid = conTocid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CON_VOUDATE", nullable=false, length=19)
    public Date getConVoudate() {
        return this.conVoudate;
    }
    
    public void setConVoudate(Date conVoudate) {
        this.conVoudate = conVoudate;
    }

    
    @Column(name="CON_NARRATION", nullable=false)
    public String getConNarration() {
        return this.conNarration;
    }
    
    public void setConNarration(String conNarration) {
        this.conNarration = conNarration;
    }

    
    @Column(name="CON_TYPE", nullable=false, length=50)
    public String getConType() {
        return this.conType;
    }
    
    public void setConType(String conType) {
        this.conType = conType;
    }

    
    @Column(name="CON_CHQNO")
    public Integer getConChqno() {
        return this.conChqno;
    }
    
    public void setConChqno(Integer conChqno) {
        this.conChqno = conChqno;
    }

    
    @Column(name="CON_CHQDATE", length=50)
    public String getConChqdate() {
        return this.conChqdate;
    }
    
    public void setConChqdate(String conChqdate) {
        this.conChqdate = conChqdate;
    }




}


