package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CourseMaster generated by hbm2java
 */
@Entity
@Table(name="course_master"
    ,catalog="e2rp"
)
public class CourseMaster  implements java.io.Serializable {


     private Integer courseId;
     private int courseautoid;
     private String teacherid;
     private String className;
     private String coursename1;
     private String coursename2;
     private String coursename3;
     private String coursefees;
     private String coursedetails;
     private String flag1;
     private String flag2;
     private String flag3;
     private String courseIsactive;

    public CourseMaster() {
    }

    public CourseMaster(int courseautoid, String teacherid, String className, String coursename1, String coursename2, String coursename3, String coursefees, String coursedetails, String flag1, String flag2, String flag3, String courseIsactive) {
       this.courseautoid = courseautoid;
       this.teacherid = teacherid;
       this.className = className;
       this.coursename1 = coursename1;
       this.coursename2 = coursename2;
       this.coursename3 = coursename3;
       this.coursefees = coursefees;
       this.coursedetails = coursedetails;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.courseIsactive = courseIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="COURSE_ID", unique=true, nullable=false)
    public Integer getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(Integer courseId) {
        this.courseId = courseId;
    }

    
    @Column(name="COURSEAUTOID", nullable=false)
    public int getCourseautoid() {
        return this.courseautoid;
    }
    
    public void setCourseautoid(int courseautoid) {
        this.courseautoid = courseautoid;
    }

    
    @Column(name="TEACHERID", nullable=false, length=50)
    public String getTeacherid() {
        return this.teacherid;
    }
    
    public void setTeacherid(String teacherid) {
        this.teacherid = teacherid;
    }

    
    @Column(name="CLASS_NAME", nullable=false, length=10)
    public String getClassName() {
        return this.className;
    }
    
    public void setClassName(String className) {
        this.className = className;
    }

    
    @Column(name="COURSENAME1", nullable=false, length=50)
    public String getCoursename1() {
        return this.coursename1;
    }
    
    public void setCoursename1(String coursename1) {
        this.coursename1 = coursename1;
    }

    
    @Column(name="COURSENAME2", nullable=false, length=50)
    public String getCoursename2() {
        return this.coursename2;
    }
    
    public void setCoursename2(String coursename2) {
        this.coursename2 = coursename2;
    }

    
    @Column(name="COURSENAME3", nullable=false, length=50)
    public String getCoursename3() {
        return this.coursename3;
    }
    
    public void setCoursename3(String coursename3) {
        this.coursename3 = coursename3;
    }

    
    @Column(name="COURSEFEES", nullable=false, length=50)
    public String getCoursefees() {
        return this.coursefees;
    }
    
    public void setCoursefees(String coursefees) {
        this.coursefees = coursefees;
    }

    
    @Column(name="COURSEDETAILS", nullable=false, length=50)
    public String getCoursedetails() {
        return this.coursedetails;
    }
    
    public void setCoursedetails(String coursedetails) {
        this.coursedetails = coursedetails;
    }

    
    @Column(name="FLAG_1", nullable=false, length=50)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", nullable=false, length=50)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", nullable=false, length=50)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="COURSE_ISACTIVE", nullable=false, length=10)
    public String getCourseIsactive() {
        return this.courseIsactive;
    }
    
    public void setCourseIsactive(String courseIsactive) {
        this.courseIsactive = courseIsactive;
    }




}


