package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DesignationMaster generated by hbm2java
 */
@Entity
@Table(name="designation_master"
    ,catalog="e2rp"
)
public class DesignationMaster  implements java.io.Serializable {


     private Integer slid;
     private String designationId;
     private String designationName;

    public DesignationMaster() {
    }

    public DesignationMaster(String designationId, String designationName) {
       this.designationId = designationId;
       this.designationName = designationName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SLID", unique=true, nullable=false)
    public Integer getSlid() {
        return this.slid;
    }
    
    public void setSlid(Integer slid) {
        this.slid = slid;
    }

    
    @Column(name="DESIGNATION_ID", nullable=false, length=250)
    public String getDesignationId() {
        return this.designationId;
    }
    
    public void setDesignationId(String designationId) {
        this.designationId = designationId;
    }

    
    @Column(name="DESIGNATION_NAME", nullable=false, length=50)
    public String getDesignationName() {
        return this.designationName;
    }
    
    public void setDesignationName(String designationName) {
        this.designationName = designationName;
    }




}


