package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enquiry generated by hbm2java
 */
@Entity
@Table(name="enquiry"
    ,catalog="e2rp"
)
public class Enquiry  implements java.io.Serializable {


     private Integer slid;
     private String enqid;
     private Date enqdate;
     private String enqmode;
     private String studentname;
     private Date dob;
     private int age;
     private String gender;
     private String guardianname;
     private String email;
     private String mobileno;
     private String class_;
     private String stream;
     private long marks;
     private String parentoccupation;
     private long annualincome;
     private String parentqualification;
     private String operatorname;
     private String reference;
     private String criteria;
     private String address;
     private String city;
     private String othercityname;
     private String state;
     private int pincode;
     private int enqstatus;
     private int followupstatus;
     private String schoolmedium;
     private String interviewdate;
     private String physicalstatus;
     private String castcata;
     private String flag4;
     private String flag5;
     private int createdby;
     private Date createdon;
     private String editedby;
     private Date editedon;
     private String enqIsactive;

    public Enquiry() {
    }

    public Enquiry(String enqid, Date enqdate, String enqmode, String studentname, Date dob, int age, String gender, String guardianname, String email, String mobileno, String class_, String stream, long marks, String parentoccupation, long annualincome, String parentqualification, String operatorname, String reference, String criteria, String address, String city, String othercityname, String state, int pincode, int enqstatus, int followupstatus, String schoolmedium, String interviewdate, String physicalstatus, String castcata, String flag4, String flag5, int createdby, Date createdon, String editedby, Date editedon, String enqIsactive) {
       this.enqid = enqid;
       this.enqdate = enqdate;
       this.enqmode = enqmode;
       this.studentname = studentname;
       this.dob = dob;
       this.age = age;
       this.gender = gender;
       this.guardianname = guardianname;
       this.email = email;
       this.mobileno = mobileno;
       this.class_ = class_;
       this.stream = stream;
       this.marks = marks;
       this.parentoccupation = parentoccupation;
       this.annualincome = annualincome;
       this.parentqualification = parentqualification;
       this.operatorname = operatorname;
       this.reference = reference;
       this.criteria = criteria;
       this.address = address;
       this.city = city;
       this.othercityname = othercityname;
       this.state = state;
       this.pincode = pincode;
       this.enqstatus = enqstatus;
       this.followupstatus = followupstatus;
       this.schoolmedium = schoolmedium;
       this.interviewdate = interviewdate;
       this.physicalstatus = physicalstatus;
       this.castcata = castcata;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.createdby = createdby;
       this.createdon = createdon;
       this.editedby = editedby;
       this.editedon = editedon;
       this.enqIsactive = enqIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SLID", unique=true, nullable=false)
    public Integer getSlid() {
        return this.slid;
    }
    
    public void setSlid(Integer slid) {
        this.slid = slid;
    }

    
    @Column(name="ENQID", nullable=false, length=30)
    public String getEnqid() {
        return this.enqid;
    }
    
    public void setEnqid(String enqid) {
        this.enqid = enqid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENQDATE", nullable=false, length=19)
    public Date getEnqdate() {
        return this.enqdate;
    }
    
    public void setEnqdate(Date enqdate) {
        this.enqdate = enqdate;
    }

    
    @Column(name="ENQMODE", nullable=false, length=20)
    public String getEnqmode() {
        return this.enqmode;
    }
    
    public void setEnqmode(String enqmode) {
        this.enqmode = enqmode;
    }

    
    @Column(name="STUDENTNAME", nullable=false, length=50)
    public String getStudentname() {
        return this.studentname;
    }
    
    public void setStudentname(String studentname) {
        this.studentname = studentname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DOB", nullable=false, length=19)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="AGE", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    
    @Column(name="GENDER", nullable=false, length=50)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="GUARDIANNAME", nullable=false, length=50)
    public String getGuardianname() {
        return this.guardianname;
    }
    
    public void setGuardianname(String guardianname) {
        this.guardianname = guardianname;
    }

    
    @Column(name="EMAIL", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="MOBILENO", nullable=false, length=20)
    public String getMobileno() {
        return this.mobileno;
    }
    
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }

    
    @Column(name="CLASS", nullable=false, length=10)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="STREAM", nullable=false, length=250)
    public String getStream() {
        return this.stream;
    }
    
    public void setStream(String stream) {
        this.stream = stream;
    }

    
    @Column(name="MARKS", nullable=false, precision=18, scale=0)
    public long getMarks() {
        return this.marks;
    }
    
    public void setMarks(long marks) {
        this.marks = marks;
    }

    
    @Column(name="PARENTOCCUPATION", nullable=false, length=50)
    public String getParentoccupation() {
        return this.parentoccupation;
    }
    
    public void setParentoccupation(String parentoccupation) {
        this.parentoccupation = parentoccupation;
    }

    
    @Column(name="ANNUALINCOME", nullable=false, precision=18, scale=0)
    public long getAnnualincome() {
        return this.annualincome;
    }
    
    public void setAnnualincome(long annualincome) {
        this.annualincome = annualincome;
    }

    
    @Column(name="PARENTQUALIFICATION", nullable=false, length=20)
    public String getParentqualification() {
        return this.parentqualification;
    }
    
    public void setParentqualification(String parentqualification) {
        this.parentqualification = parentqualification;
    }

    
    @Column(name="OPERATORNAME", nullable=false, length=20)
    public String getOperatorname() {
        return this.operatorname;
    }
    
    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname;
    }

    
    @Column(name="REFERENCE", nullable=false, length=30)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    
    @Column(name="CRITERIA", nullable=false, length=250)
    public String getCriteria() {
        return this.criteria;
    }
    
    public void setCriteria(String criteria) {
        this.criteria = criteria;
    }

    
    @Column(name="ADDRESS", nullable=false, length=250)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="CITY", nullable=false, length=250)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="OTHERCITYNAME", nullable=false, length=30)
    public String getOthercityname() {
        return this.othercityname;
    }
    
    public void setOthercityname(String othercityname) {
        this.othercityname = othercityname;
    }

    
    @Column(name="STATE", nullable=false, length=30)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="PINCODE", nullable=false)
    public int getPincode() {
        return this.pincode;
    }
    
    public void setPincode(int pincode) {
        this.pincode = pincode;
    }

    
    @Column(name="ENQSTATUS", nullable=false)
    public int getEnqstatus() {
        return this.enqstatus;
    }
    
    public void setEnqstatus(int enqstatus) {
        this.enqstatus = enqstatus;
    }

    
    @Column(name="FOLLOWUPSTATUS", nullable=false)
    public int getFollowupstatus() {
        return this.followupstatus;
    }
    
    public void setFollowupstatus(int followupstatus) {
        this.followupstatus = followupstatus;
    }

    
    @Column(name="SCHOOLMEDIUM", nullable=false, length=30)
    public String getSchoolmedium() {
        return this.schoolmedium;
    }
    
    public void setSchoolmedium(String schoolmedium) {
        this.schoolmedium = schoolmedium;
    }

    
    @Column(name="INTERVIEWDATE", nullable=false, length=30)
    public String getInterviewdate() {
        return this.interviewdate;
    }
    
    public void setInterviewdate(String interviewdate) {
        this.interviewdate = interviewdate;
    }

    
    @Column(name="PHYSICALSTATUS", nullable=false, length=30)
    public String getPhysicalstatus() {
        return this.physicalstatus;
    }
    
    public void setPhysicalstatus(String physicalstatus) {
        this.physicalstatus = physicalstatus;
    }

    
    @Column(name="CASTCATA", nullable=false, length=30)
    public String getCastcata() {
        return this.castcata;
    }
    
    public void setCastcata(String castcata) {
        this.castcata = castcata;
    }

    
    @Column(name="FLAG_4", nullable=false, length=30)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }

    
    @Column(name="FLAG_5", nullable=false, length=30)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }

    
    @Column(name="CREATEDBY", nullable=false)
    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDON", nullable=false, length=19)
    public Date getCreatedon() {
        return this.createdon;
    }
    
    public void setCreatedon(Date createdon) {
        this.createdon = createdon;
    }

    
    @Column(name="EDITEDBY", nullable=false, length=30)
    public String getEditedby() {
        return this.editedby;
    }
    
    public void setEditedby(String editedby) {
        this.editedby = editedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EDITEDON", nullable=false, length=19)
    public Date getEditedon() {
        return this.editedon;
    }
    
    public void setEditedon(Date editedon) {
        this.editedon = editedon;
    }

    
    @Column(name="ENQ_ISACTIVE", nullable=false, length=30)
    public String getEnqIsactive() {
        return this.enqIsactive;
    }
    
    public void setEnqIsactive(String enqIsactive) {
        this.enqIsactive = enqIsactive;
    }




}


