package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Examschedule generated by hbm2java
 */
@Entity
@Table(name="examschedule"
    ,catalog="e2rp"
)
public class Examschedule  implements java.io.Serializable {


     private Integer scheduleId;
     private String examType;
     private String stream;
     private Date date;
     private Date startingTime;
     private int classId;
     private int subjectId;
     private int duration;
     private String durationHms;

    public Examschedule() {
    }

    public Examschedule(String examType, String stream, Date date, Date startingTime, int classId, int subjectId, int duration, String durationHms) {
       this.examType = examType;
       this.stream = stream;
       this.date = date;
       this.startingTime = startingTime;
       this.classId = classId;
       this.subjectId = subjectId;
       this.duration = duration;
       this.durationHms = durationHms;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SCHEDULE_ID", unique=true, nullable=false)
    public Integer getScheduleId() {
        return this.scheduleId;
    }
    
    public void setScheduleId(Integer scheduleId) {
        this.scheduleId = scheduleId;
    }

    
    @Column(name="EXAM_TYPE", nullable=false, length=50)
    public String getExamType() {
        return this.examType;
    }
    
    public void setExamType(String examType) {
        this.examType = examType;
    }

    
    @Column(name="STREAM", nullable=false, length=50)
    public String getStream() {
        return this.stream;
    }
    
    public void setStream(String stream) {
        this.stream = stream;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STARTING_TIME", nullable=false, length=19)
    public Date getStartingTime() {
        return this.startingTime;
    }
    
    public void setStartingTime(Date startingTime) {
        this.startingTime = startingTime;
    }

    
    @Column(name="CLASS_ID", nullable=false)
    public int getClassId() {
        return this.classId;
    }
    
    public void setClassId(int classId) {
        this.classId = classId;
    }

    
    @Column(name="SUBJECT_ID", nullable=false)
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }

    
    @Column(name="DURATION", nullable=false)
    public int getDuration() {
        return this.duration;
    }
    
    public void setDuration(int duration) {
        this.duration = duration;
    }

    
    @Column(name="DURATION_HMS", nullable=false, length=50)
    public String getDurationHms() {
        return this.durationHms;
    }
    
    public void setDurationHms(String durationHms) {
        this.durationHms = durationHms;
    }




}


