package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FeesMaster generated by hbm2java
 */
@Entity
@Table(name="fees_master"
    ,catalog="e2rp"
)
public class FeesMaster  implements java.io.Serializable {


     private Integer feesId;
     private String class_;
     private BigDecimal admissionFee;
     private BigDecimal tutionFee;
     private BigDecimal computerFee;
     private BigDecimal devlopmentFee;
     private BigDecimal cautonMoney;
     private BigDecimal anualMusic;
     private BigDecimal medicalFee;
     private BigDecimal total;
     private Integer createdBy;
     private Date createdOn;
     private String feesIsactive;

    public FeesMaster() {
    }

	
    public FeesMaster(String class_, BigDecimal admissionFee, BigDecimal tutionFee, BigDecimal computerFee, BigDecimal devlopmentFee, BigDecimal cautonMoney, BigDecimal anualMusic, BigDecimal medicalFee, BigDecimal total, Date createdOn, String feesIsactive) {
        this.class_ = class_;
        this.admissionFee = admissionFee;
        this.tutionFee = tutionFee;
        this.computerFee = computerFee;
        this.devlopmentFee = devlopmentFee;
        this.cautonMoney = cautonMoney;
        this.anualMusic = anualMusic;
        this.medicalFee = medicalFee;
        this.total = total;
        this.createdOn = createdOn;
        this.feesIsactive = feesIsactive;
    }
    public FeesMaster(String class_, BigDecimal admissionFee, BigDecimal tutionFee, BigDecimal computerFee, BigDecimal devlopmentFee, BigDecimal cautonMoney, BigDecimal anualMusic, BigDecimal medicalFee, BigDecimal total, Integer createdBy, Date createdOn, String feesIsactive) {
       this.class_ = class_;
       this.admissionFee = admissionFee;
       this.tutionFee = tutionFee;
       this.computerFee = computerFee;
       this.devlopmentFee = devlopmentFee;
       this.cautonMoney = cautonMoney;
       this.anualMusic = anualMusic;
       this.medicalFee = medicalFee;
       this.total = total;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.feesIsactive = feesIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="FEES_ID", unique=true, nullable=false)
    public Integer getFeesId() {
        return this.feesId;
    }
    
    public void setFeesId(Integer feesId) {
        this.feesId = feesId;
    }

    
    @Column(name="CLASS", nullable=false, length=20)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="ADMISSION_FEE", nullable=false, precision=18)
    public BigDecimal getAdmissionFee() {
        return this.admissionFee;
    }
    
    public void setAdmissionFee(BigDecimal admissionFee) {
        this.admissionFee = admissionFee;
    }

    
    @Column(name="TUTION_FEE", nullable=false, precision=18)
    public BigDecimal getTutionFee() {
        return this.tutionFee;
    }
    
    public void setTutionFee(BigDecimal tutionFee) {
        this.tutionFee = tutionFee;
    }

    
    @Column(name="COMPUTER_FEE", nullable=false, precision=18)
    public BigDecimal getComputerFee() {
        return this.computerFee;
    }
    
    public void setComputerFee(BigDecimal computerFee) {
        this.computerFee = computerFee;
    }

    
    @Column(name="DEVLOPMENT_FEE", nullable=false, precision=18)
    public BigDecimal getDevlopmentFee() {
        return this.devlopmentFee;
    }
    
    public void setDevlopmentFee(BigDecimal devlopmentFee) {
        this.devlopmentFee = devlopmentFee;
    }

    
    @Column(name="CAUTON_MONEY", nullable=false, precision=18)
    public BigDecimal getCautonMoney() {
        return this.cautonMoney;
    }
    
    public void setCautonMoney(BigDecimal cautonMoney) {
        this.cautonMoney = cautonMoney;
    }

    
    @Column(name="ANUAL_MUSIC", nullable=false, precision=18)
    public BigDecimal getAnualMusic() {
        return this.anualMusic;
    }
    
    public void setAnualMusic(BigDecimal anualMusic) {
        this.anualMusic = anualMusic;
    }

    
    @Column(name="MEDICAL_FEE", nullable=false, precision=18)
    public BigDecimal getMedicalFee() {
        return this.medicalFee;
    }
    
    public void setMedicalFee(BigDecimal medicalFee) {
        this.medicalFee = medicalFee;
    }

    
    @Column(name="TOTAL", nullable=false, precision=18)
    public BigDecimal getTotal() {
        return this.total;
    }
    
    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    
    @Column(name="CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_ON", nullable=false, length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="FEES_ISACTIVE", nullable=false, length=2)
    public String getFeesIsactive() {
        return this.feesIsactive;
    }
    
    public void setFeesIsactive(String feesIsactive) {
        this.feesIsactive = feesIsactive;
    }




}


