package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Finesetting generated by hbm2java
 */
@Entity
@Table(name="finesetting"
    ,catalog="e2rp"
)
public class Finesetting  implements java.io.Serializable {


     private Integer memtypeId;
     private String memberType;
     private int dueDay;
     private BigDecimal finePerday;

    public Finesetting() {
    }

    public Finesetting(String memberType, int dueDay, BigDecimal finePerday) {
       this.memberType = memberType;
       this.dueDay = dueDay;
       this.finePerday = finePerday;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MEMTYPE_ID", unique=true, nullable=false)
    public Integer getMemtypeId() {
        return this.memtypeId;
    }
    
    public void setMemtypeId(Integer memtypeId) {
        this.memtypeId = memtypeId;
    }

    
    @Column(name="MEMBER_TYPE", nullable=false, length=50)
    public String getMemberType() {
        return this.memberType;
    }
    
    public void setMemberType(String memberType) {
        this.memberType = memberType;
    }

    
    @Column(name="DUE_DAY", nullable=false)
    public int getDueDay() {
        return this.dueDay;
    }
    
    public void setDueDay(int dueDay) {
        this.dueDay = dueDay;
    }

    
    @Column(name="FINE_PERDAY", nullable=false, precision=18)
    public BigDecimal getFinePerday() {
        return this.finePerday;
    }
    
    public void setFinePerday(BigDecimal finePerday) {
        this.finePerday = finePerday;
    }




}


