package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * FloorMaster generated by hbm2java
 */
@Entity
@Table(name="floor_master"
    ,catalog="e2rp"
)
public class FloorMaster  implements java.io.Serializable {


     private Integer floorId;
     private String floorName;
     private int buildingId;
     private String flag1;
     private String flag2;
     private String flag3;
     private String floorIsactive;

    public FloorMaster() {
    }

    public FloorMaster(String floorName, int buildingId, String flag1, String flag2, String flag3, String floorIsactive) {
       this.floorName = floorName;
       this.buildingId = buildingId;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.floorIsactive = floorIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="FLOOR_ID", unique=true, nullable=false)
    public Integer getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(Integer floorId) {
        this.floorId = floorId;
    }

    
    @Column(name="FLOOR_NAME", nullable=false, length=50)
    public String getFloorName() {
        return this.floorName;
    }
    
    public void setFloorName(String floorName) {
        this.floorName = floorName;
    }

    
    @Column(name="BUILDING_ID", nullable=false)
    public int getBuildingId() {
        return this.buildingId;
    }
    
    public void setBuildingId(int buildingId) {
        this.buildingId = buildingId;
    }

    
    @Column(name="FLAG_1", nullable=false, length=50)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", nullable=false, length=50)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", nullable=false, length=50)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="FLOOR_ISACTIVE", nullable=false, length=10)
    public String getFloorIsactive() {
        return this.floorIsactive;
    }
    
    public void setFloorIsactive(String floorIsactive) {
        this.floorIsactive = floorIsactive;
    }




}


