package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InterviewDateCopy generated by hbm2java
 */
@Entity
@Table(name="interview_date_copy"
    ,catalog="e2rp"
)
public class InterviewDateCopy  implements java.io.Serializable {


     private Integer postId;
     private String postName;
     private String interviewDate;

    public InterviewDateCopy() {
    }

    public InterviewDateCopy(String postName, String interviewDate) {
       this.postName = postName;
       this.interviewDate = interviewDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="POST_ID", unique=true, nullable=false)
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    
    @Column(name="POST_NAME", length=50)
    public String getPostName() {
        return this.postName;
    }
    
    public void setPostName(String postName) {
        this.postName = postName;
    }

    
    @Column(name="INTERVIEW_DATE", length=50)
    public String getInterviewDate() {
        return this.interviewDate;
    }
    
    public void setInterviewDate(String interviewDate) {
        this.interviewDate = interviewDate;
    }




}


