package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Itemdtl generated by hbm2java
 */
@Entity
@Table(name="itemdtl"
    ,catalog="e2rp"
)
public class Itemdtl  implements java.io.Serializable {


     private ItemdtlId id;
     private BigDecimal itemPurrate;
     private String itemPurrateuom;
     private BigDecimal itemSalerate;
     private String itemSalerateuom;
     private Date itemFromdt;
     private Date itemTodt;

    public Itemdtl() {
    }

	
    public Itemdtl(ItemdtlId id, String itemPurrateuom, String itemSalerateuom, Date itemFromdt) {
        this.id = id;
        this.itemPurrateuom = itemPurrateuom;
        this.itemSalerateuom = itemSalerateuom;
        this.itemFromdt = itemFromdt;
    }
    public Itemdtl(ItemdtlId id, BigDecimal itemPurrate, String itemPurrateuom, BigDecimal itemSalerate, String itemSalerateuom, Date itemFromdt, Date itemTodt) {
       this.id = id;
       this.itemPurrate = itemPurrate;
       this.itemPurrateuom = itemPurrateuom;
       this.itemSalerate = itemSalerate;
       this.itemSalerateuom = itemSalerateuom;
       this.itemFromdt = itemFromdt;
       this.itemTodt = itemTodt;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="itemDtlid", column=@Column(name="ITEM_DTLID", nullable=false) ), 
        @AttributeOverride(name="itemId", column=@Column(name="ITEM_ID", nullable=false) ) } )
    public ItemdtlId getId() {
        return this.id;
    }
    
    public void setId(ItemdtlId id) {
        this.id = id;
    }

    
    @Column(name="ITEM_PURRATE", precision=18)
    public BigDecimal getItemPurrate() {
        return this.itemPurrate;
    }
    
    public void setItemPurrate(BigDecimal itemPurrate) {
        this.itemPurrate = itemPurrate;
    }

    
    @Column(name="ITEM_PURRATEUOM", nullable=false, length=10)
    public String getItemPurrateuom() {
        return this.itemPurrateuom;
    }
    
    public void setItemPurrateuom(String itemPurrateuom) {
        this.itemPurrateuom = itemPurrateuom;
    }

    
    @Column(name="ITEM_SALERATE", precision=18)
    public BigDecimal getItemSalerate() {
        return this.itemSalerate;
    }
    
    public void setItemSalerate(BigDecimal itemSalerate) {
        this.itemSalerate = itemSalerate;
    }

    
    @Column(name="ITEM_SALERATEUOM", nullable=false, length=10)
    public String getItemSalerateuom() {
        return this.itemSalerateuom;
    }
    
    public void setItemSalerateuom(String itemSalerateuom) {
        this.itemSalerateuom = itemSalerateuom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ITEM_FROMDT", nullable=false, length=19)
    public Date getItemFromdt() {
        return this.itemFromdt;
    }
    
    public void setItemFromdt(Date itemFromdt) {
        this.itemFromdt = itemFromdt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ITEM_TODT", length=19)
    public Date getItemTodt() {
        return this.itemTodt;
    }
    
    public void setItemTodt(Date itemTodt) {
        this.itemTodt = itemTodt;
    }




}


