package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemdtlId generated by hbm2java
 */
@Embeddable
public class ItemdtlId  implements java.io.Serializable {


     private int itemDtlid;
     private int itemId;

    public ItemdtlId() {
    }

    public ItemdtlId(int itemDtlid, int itemId) {
       this.itemDtlid = itemDtlid;
       this.itemId = itemId;
    }
   


    @Column(name="ITEM_DTLID", nullable=false)
    public int getItemDtlid() {
        return this.itemDtlid;
    }
    
    public void setItemDtlid(int itemDtlid) {
        this.itemDtlid = itemDtlid;
    }


    @Column(name="ITEM_ID", nullable=false)
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ItemdtlId) ) return false;
		 ItemdtlId castOther = ( ItemdtlId ) other; 
         
		 return (this.getItemDtlid()==castOther.getItemDtlid())
 && (this.getItemId()==castOther.getItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getItemDtlid();
         result = 37 * result + this.getItemId();
         return result;
   }   


}


