package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JobApplication generated by hbm2java
 */
@Entity
@Table(name="job_application"
    ,catalog="e2rp"
)
public class JobApplication  implements java.io.Serializable {


     private Integer applicationId;
     private int adId;
     private String applicantName;
     private String contactNo;
     private String email;
     private String address;
     private String highestQualification;
     private String specialization;
     private String experience;
     private Date applicationDate;
     private int appFlag1;
     private int appFlag2;
     private String appIsactive;

    public JobApplication() {
    }

	
    public JobApplication(int adId, String applicantName, String contactNo, String email, String address, String highestQualification, String specialization, String experience, int appFlag1, int appFlag2, String appIsactive) {
        this.adId = adId;
        this.applicantName = applicantName;
        this.contactNo = contactNo;
        this.email = email;
        this.address = address;
        this.highestQualification = highestQualification;
        this.specialization = specialization;
        this.experience = experience;
        this.appFlag1 = appFlag1;
        this.appFlag2 = appFlag2;
        this.appIsactive = appIsactive;
    }
    public JobApplication(int adId, String applicantName, String contactNo, String email, String address, String highestQualification, String specialization, String experience, Date applicationDate, int appFlag1, int appFlag2, String appIsactive) {
       this.adId = adId;
       this.applicantName = applicantName;
       this.contactNo = contactNo;
       this.email = email;
       this.address = address;
       this.highestQualification = highestQualification;
       this.specialization = specialization;
       this.experience = experience;
       this.applicationDate = applicationDate;
       this.appFlag1 = appFlag1;
       this.appFlag2 = appFlag2;
       this.appIsactive = appIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="APPLICATION_ID", unique=true, nullable=false)
    public Integer getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(Integer applicationId) {
        this.applicationId = applicationId;
    }

    
    @Column(name="AD_ID", nullable=false)
    public int getAdId() {
        return this.adId;
    }
    
    public void setAdId(int adId) {
        this.adId = adId;
    }

    
    @Column(name="APPLICANT_NAME", nullable=false, length=50)
    public String getApplicantName() {
        return this.applicantName;
    }
    
    public void setApplicantName(String applicantName) {
        this.applicantName = applicantName;
    }

    
    @Column(name="CONTACT_NO", nullable=false, length=50)
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }

    
    @Column(name="EMAIL", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="ADDRESS", nullable=false, length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="HIGHEST_QUALIFICATION", nullable=false, length=50)
    public String getHighestQualification() {
        return this.highestQualification;
    }
    
    public void setHighestQualification(String highestQualification) {
        this.highestQualification = highestQualification;
    }

    
    @Column(name="SPECIALIZATION", nullable=false, length=50)
    public String getSpecialization() {
        return this.specialization;
    }
    
    public void setSpecialization(String specialization) {
        this.specialization = specialization;
    }

    
    @Column(name="EXPERIENCE", nullable=false, length=50)
    public String getExperience() {
        return this.experience;
    }
    
    public void setExperience(String experience) {
        this.experience = experience;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="APPLICATION_DATE", length=10)
    public Date getApplicationDate() {
        return this.applicationDate;
    }
    
    public void setApplicationDate(Date applicationDate) {
        this.applicationDate = applicationDate;
    }

    
    @Column(name="APP_FLAG_1", nullable=false)
    public int getAppFlag1() {
        return this.appFlag1;
    }
    
    public void setAppFlag1(int appFlag1) {
        this.appFlag1 = appFlag1;
    }

    
    @Column(name="APP_FLAG_2", nullable=false)
    public int getAppFlag2() {
        return this.appFlag2;
    }
    
    public void setAppFlag2(int appFlag2) {
        this.appFlag2 = appFlag2;
    }

    
    @Column(name="APP_ISACTIVE", nullable=false, length=30)
    public String getAppIsactive() {
        return this.appIsactive;
    }
    
    public void setAppIsactive(String appIsactive) {
        this.appIsactive = appIsactive;
    }




}


