package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JournaldetailsId generated by hbm2java
 */
@Embeddable
public class JournaldetailsId  implements java.io.Serializable {


     private int jouDtlid;
     private int jouId;

    public JournaldetailsId() {
    }

    public JournaldetailsId(int jouDtlid, int jouId) {
       this.jouDtlid = jouDtlid;
       this.jouId = jouId;
    }
   


    @Column(name="JOU_DTLID", nullable=false)
    public int getJouDtlid() {
        return this.jouDtlid;
    }
    
    public void setJouDtlid(int jouDtlid) {
        this.jouDtlid = jouDtlid;
    }


    @Column(name="JOU_ID", nullable=false)
    public int getJouId() {
        return this.jouId;
    }
    
    public void setJouId(int jouId) {
        this.jouId = jouId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof JournaldetailsId) ) return false;
		 JournaldetailsId castOther = ( JournaldetailsId ) other; 
         
		 return (this.getJouDtlid()==castOther.getJouDtlid())
 && (this.getJouId()==castOther.getJouId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getJouDtlid();
         result = 37 * result + this.getJouId();
         return result;
   }   


}


