package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Journalmaster generated by hbm2java
 */
@Entity
@Table(name="journalmaster"
    ,catalog="e2rp"
)
public class Journalmaster  implements java.io.Serializable {


     private Integer jouId;
     private int jouCodeid;
     private String jouCode;
     private int jouTocid;
     private Date jouVoudate;
     private String jouNarration;
     private String jouType;
     private Integer jouChqno;
     private String jouChqdate;

    public Journalmaster() {
    }

	
    public Journalmaster(int jouCodeid, String jouCode, int jouTocid, Date jouVoudate, String jouNarration, String jouType) {
        this.jouCodeid = jouCodeid;
        this.jouCode = jouCode;
        this.jouTocid = jouTocid;
        this.jouVoudate = jouVoudate;
        this.jouNarration = jouNarration;
        this.jouType = jouType;
    }
    public Journalmaster(int jouCodeid, String jouCode, int jouTocid, Date jouVoudate, String jouNarration, String jouType, Integer jouChqno, String jouChqdate) {
       this.jouCodeid = jouCodeid;
       this.jouCode = jouCode;
       this.jouTocid = jouTocid;
       this.jouVoudate = jouVoudate;
       this.jouNarration = jouNarration;
       this.jouType = jouType;
       this.jouChqno = jouChqno;
       this.jouChqdate = jouChqdate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="JOU_ID", unique=true, nullable=false)
    public Integer getJouId() {
        return this.jouId;
    }
    
    public void setJouId(Integer jouId) {
        this.jouId = jouId;
    }

    
    @Column(name="JOU_CODEID", nullable=false)
    public int getJouCodeid() {
        return this.jouCodeid;
    }
    
    public void setJouCodeid(int jouCodeid) {
        this.jouCodeid = jouCodeid;
    }

    
    @Column(name="JOU_CODE", nullable=false, length=20)
    public String getJouCode() {
        return this.jouCode;
    }
    
    public void setJouCode(String jouCode) {
        this.jouCode = jouCode;
    }

    
    @Column(name="JOU_TOCID", nullable=false)
    public int getJouTocid() {
        return this.jouTocid;
    }
    
    public void setJouTocid(int jouTocid) {
        this.jouTocid = jouTocid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="JOU_VOUDATE", nullable=false, length=19)
    public Date getJouVoudate() {
        return this.jouVoudate;
    }
    
    public void setJouVoudate(Date jouVoudate) {
        this.jouVoudate = jouVoudate;
    }

    
    @Column(name="JOU_NARRATION", nullable=false)
    public String getJouNarration() {
        return this.jouNarration;
    }
    
    public void setJouNarration(String jouNarration) {
        this.jouNarration = jouNarration;
    }

    
    @Column(name="JOU_TYPE", nullable=false, length=50)
    public String getJouType() {
        return this.jouType;
    }
    
    public void setJouType(String jouType) {
        this.jouType = jouType;
    }

    
    @Column(name="JOU_CHQNO")
    public Integer getJouChqno() {
        return this.jouChqno;
    }
    
    public void setJouChqno(Integer jouChqno) {
        this.jouChqno = jouChqno;
    }

    
    @Column(name="JOU_CHQDATE", length=50)
    public String getJouChqdate() {
        return this.jouChqdate;
    }
    
    public void setJouChqdate(String jouChqdate) {
        this.jouChqdate = jouChqdate;
    }




}


