package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LandMaster generated by hbm2java
 */
@Entity
@Table(name="land_master"
    ,catalog="e2rp"
)
public class LandMaster  implements java.io.Serializable {


     private Integer landId;
     private String landName;
     private String landAddress;
     private String flag1;
     private String flag2;
     private String flag3;
     private String landIsactive;

    public LandMaster() {
    }

    public LandMaster(String landName, String landAddress, String flag1, String flag2, String flag3, String landIsactive) {
       this.landName = landName;
       this.landAddress = landAddress;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.landIsactive = landIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="LAND_ID", unique=true, nullable=false)
    public Integer getLandId() {
        return this.landId;
    }
    
    public void setLandId(Integer landId) {
        this.landId = landId;
    }

    
    @Column(name="LAND_NAME", nullable=false, length=50)
    public String getLandName() {
        return this.landName;
    }
    
    public void setLandName(String landName) {
        this.landName = landName;
    }

    
    @Column(name="LAND_ADDRESS", nullable=false, length=50)
    public String getLandAddress() {
        return this.landAddress;
    }
    
    public void setLandAddress(String landAddress) {
        this.landAddress = landAddress;
    }

    
    @Column(name="FLAG_1", nullable=false, length=50)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", nullable=false, length=50)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", nullable=false, length=50)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="LAND_ISACTIVE", nullable=false, length=10)
    public String getLandIsactive() {
        return this.landIsactive;
    }
    
    public void setLandIsactive(String landIsactive) {
        this.landIsactive = landIsactive;
    }




}


