package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LedgercrTbl generated by hbm2java
 */
@Entity
@Table(name="ledgercr_tbl"
    ,catalog="e2rp"
)
public class LedgercrTbl  implements java.io.Serializable {


     private Integer id;
     private String ledgerDate;
     private String ledgerParticulars;
     private String ledgerAmo;

    public LedgercrTbl() {
    }

    public LedgercrTbl(String ledgerDate, String ledgerParticulars, String ledgerAmo) {
       this.ledgerDate = ledgerDate;
       this.ledgerParticulars = ledgerParticulars;
       this.ledgerAmo = ledgerAmo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="LEDGER_DATE", length=50)
    public String getLedgerDate() {
        return this.ledgerDate;
    }
    
    public void setLedgerDate(String ledgerDate) {
        this.ledgerDate = ledgerDate;
    }

    
    @Column(name="LEDGER_PARTICULARS", length=250)
    public String getLedgerParticulars() {
        return this.ledgerParticulars;
    }
    
    public void setLedgerParticulars(String ledgerParticulars) {
        this.ledgerParticulars = ledgerParticulars;
    }

    
    @Column(name="LEDGER_AMO", length=50)
    public String getLedgerAmo() {
        return this.ledgerAmo;
    }
    
    public void setLedgerAmo(String ledgerAmo) {
        this.ledgerAmo = ledgerAmo;
    }




}


