package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LiabilityTable generated by hbm2java
 */
@Entity
@Table(name="liability_table"
    ,catalog="e2rp"
)
public class LiabilityTable  implements java.io.Serializable {


     private Integer id;
     private String libDate;
     private String libParticulars;
     private String libAmo;

    public LiabilityTable() {
    }

    public LiabilityTable(String libDate, String libParticulars, String libAmo) {
       this.libDate = libDate;
       this.libParticulars = libParticulars;
       this.libAmo = libAmo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="LIB_DATE", length=50)
    public String getLibDate() {
        return this.libDate;
    }
    
    public void setLibDate(String libDate) {
        this.libDate = libDate;
    }

    
    @Column(name="LIB_PARTICULARS", length=250)
    public String getLibParticulars() {
        return this.libParticulars;
    }
    
    public void setLibParticulars(String libParticulars) {
        this.libParticulars = libParticulars;
    }

    
    @Column(name="LIB_AMO", length=50)
    public String getLibAmo() {
        return this.libAmo;
    }
    
    public void setLibAmo(String libAmo) {
        this.libAmo = libAmo;
    }




}


