package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
    ,catalog="e2rp"
)
public class Login  implements java.io.Serializable {


     private Integer loginId;
     private String loginUsername;
     private String loginPassword;
     private String loginRole;
     private Integer createdBy;
     private Date createdOn;
     private String classIsactive;
     private String presentStatus;

    public Login() {
    }

	
    public Login(String loginUsername, String loginPassword, String loginRole, Date createdOn, String classIsactive) {
        this.loginUsername = loginUsername;
        this.loginPassword = loginPassword;
        this.loginRole = loginRole;
        this.createdOn = createdOn;
        this.classIsactive = classIsactive;
    }
    public Login(String loginUsername, String loginPassword, String loginRole, Integer createdBy, Date createdOn, String classIsactive, String presentStatus) {
       this.loginUsername = loginUsername;
       this.loginPassword = loginPassword;
       this.loginRole = loginRole;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.classIsactive = classIsactive;
       this.presentStatus = presentStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="LOGIN_ID", unique=true, nullable=false)
    public Integer getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

    
    @Column(name="LOGIN_USERNAME", nullable=false, length=20)
    public String getLoginUsername() {
        return this.loginUsername;
    }
    
    public void setLoginUsername(String loginUsername) {
        this.loginUsername = loginUsername;
    }

    
    @Column(name="LOGIN_PASSWORD", nullable=false, length=20)
    public String getLoginPassword() {
        return this.loginPassword;
    }
    
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword;
    }

    
    @Column(name="LOGIN_ROLE", nullable=false, length=20)
    public String getLoginRole() {
        return this.loginRole;
    }
    
    public void setLoginRole(String loginRole) {
        this.loginRole = loginRole;
    }

    
    @Column(name="CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_ON", nullable=false, length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="CLASS_ISACTIVE", nullable=false, length=10)
    public String getClassIsactive() {
        return this.classIsactive;
    }
    
    public void setClassIsactive(String classIsactive) {
        this.classIsactive = classIsactive;
    }

    
    @Column(name="PRESENT STATUS", length=10)
    public String getPresentStatus() {
        return this.presentStatus;
    }
    
    public void setPresentStatus(String presentStatus) {
        this.presentStatus = presentStatus;
    }




}


