package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MarksMaster generated by hbm2java
 */
@Entity
@Table(name="marks_master"
    ,catalog="e2rp"
)
public class MarksMaster  implements java.io.Serializable {


     private Integer marksId;
     private int studentId;

    public MarksMaster() {
    }

    public MarksMaster(int studentId) {
       this.studentId = studentId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MARKS_ID", unique=true, nullable=false)
    public Integer getMarksId() {
        return this.marksId;
    }
    
    public void setMarksId(Integer marksId) {
        this.marksId = marksId;
    }

    
    @Column(name="STUDENT_ID", nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }




}


