package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Paymentdetails generated by hbm2java
 */
@Entity
@Table(name="paymentdetails"
    ,catalog="e2rp"
)
public class Paymentdetails  implements java.io.Serializable {


     private PaymentdetailsId id;
     private String pymByorto;
     private String pymNature;
     private String pymParticulars;
     private int pymAccId;
     private BigDecimal pymDramount;
     private BigDecimal pymCramount;

    public Paymentdetails() {
    }

	
    public Paymentdetails(PaymentdetailsId id, String pymByorto, String pymNature, String pymParticulars, int pymAccId) {
        this.id = id;
        this.pymByorto = pymByorto;
        this.pymNature = pymNature;
        this.pymParticulars = pymParticulars;
        this.pymAccId = pymAccId;
    }
    public Paymentdetails(PaymentdetailsId id, String pymByorto, String pymNature, String pymParticulars, int pymAccId, BigDecimal pymDramount, BigDecimal pymCramount) {
       this.id = id;
       this.pymByorto = pymByorto;
       this.pymNature = pymNature;
       this.pymParticulars = pymParticulars;
       this.pymAccId = pymAccId;
       this.pymDramount = pymDramount;
       this.pymCramount = pymCramount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="pymDtlid", column=@Column(name="PYM_DTLID", nullable=false) ), 
        @AttributeOverride(name="pymId", column=@Column(name="PYM_ID", nullable=false) ) } )
    public PaymentdetailsId getId() {
        return this.id;
    }
    
    public void setId(PaymentdetailsId id) {
        this.id = id;
    }

    
    @Column(name="PYM_BYORTO", nullable=false, length=20)
    public String getPymByorto() {
        return this.pymByorto;
    }
    
    public void setPymByorto(String pymByorto) {
        this.pymByorto = pymByorto;
    }

    
    @Column(name="PYM_NATURE", nullable=false, length=50)
    public String getPymNature() {
        return this.pymNature;
    }
    
    public void setPymNature(String pymNature) {
        this.pymNature = pymNature;
    }

    
    @Column(name="PYM_PARTICULARS", nullable=false, length=50)
    public String getPymParticulars() {
        return this.pymParticulars;
    }
    
    public void setPymParticulars(String pymParticulars) {
        this.pymParticulars = pymParticulars;
    }

    
    @Column(name="PYM_ACC_ID", nullable=false)
    public int getPymAccId() {
        return this.pymAccId;
    }
    
    public void setPymAccId(int pymAccId) {
        this.pymAccId = pymAccId;
    }

    
    @Column(name="PYM_DRAMOUNT", precision=18)
    public BigDecimal getPymDramount() {
        return this.pymDramount;
    }
    
    public void setPymDramount(BigDecimal pymDramount) {
        this.pymDramount = pymDramount;
    }

    
    @Column(name="PYM_CRAMOUNT", precision=18)
    public BigDecimal getPymCramount() {
        return this.pymCramount;
    }
    
    public void setPymCramount(BigDecimal pymCramount) {
        this.pymCramount = pymCramount;
    }




}


