package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Paymentmaster generated by hbm2java
 */
@Entity
@Table(name="paymentmaster"
    ,catalog="e2rp"
)
public class Paymentmaster  implements java.io.Serializable {


     private Integer pymId;
     private int pymCodeid;
     private String pymCode;
     private int pymTocid;
     private Date pymVoudate;
     private String pymNarration;
     private String pymType;
     private Integer pymChqno;
     private String pymChqdate;

    public Paymentmaster() {
    }

	
    public Paymentmaster(int pymCodeid, String pymCode, int pymTocid, Date pymVoudate, String pymNarration, String pymType) {
        this.pymCodeid = pymCodeid;
        this.pymCode = pymCode;
        this.pymTocid = pymTocid;
        this.pymVoudate = pymVoudate;
        this.pymNarration = pymNarration;
        this.pymType = pymType;
    }
    public Paymentmaster(int pymCodeid, String pymCode, int pymTocid, Date pymVoudate, String pymNarration, String pymType, Integer pymChqno, String pymChqdate) {
       this.pymCodeid = pymCodeid;
       this.pymCode = pymCode;
       this.pymTocid = pymTocid;
       this.pymVoudate = pymVoudate;
       this.pymNarration = pymNarration;
       this.pymType = pymType;
       this.pymChqno = pymChqno;
       this.pymChqdate = pymChqdate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PYM_ID", unique=true, nullable=false)
    public Integer getPymId() {
        return this.pymId;
    }
    
    public void setPymId(Integer pymId) {
        this.pymId = pymId;
    }

    
    @Column(name="PYM_CODEID", nullable=false)
    public int getPymCodeid() {
        return this.pymCodeid;
    }
    
    public void setPymCodeid(int pymCodeid) {
        this.pymCodeid = pymCodeid;
    }

    
    @Column(name="PYM_CODE", nullable=false, length=20)
    public String getPymCode() {
        return this.pymCode;
    }
    
    public void setPymCode(String pymCode) {
        this.pymCode = pymCode;
    }

    
    @Column(name="PYM_TOCID", nullable=false)
    public int getPymTocid() {
        return this.pymTocid;
    }
    
    public void setPymTocid(int pymTocid) {
        this.pymTocid = pymTocid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PYM_VOUDATE", nullable=false, length=19)
    public Date getPymVoudate() {
        return this.pymVoudate;
    }
    
    public void setPymVoudate(Date pymVoudate) {
        this.pymVoudate = pymVoudate;
    }

    
    @Column(name="PYM_NARRATION", nullable=false)
    public String getPymNarration() {
        return this.pymNarration;
    }
    
    public void setPymNarration(String pymNarration) {
        this.pymNarration = pymNarration;
    }

    
    @Column(name="PYM_TYPE", nullable=false, length=50)
    public String getPymType() {
        return this.pymType;
    }
    
    public void setPymType(String pymType) {
        this.pymType = pymType;
    }

    
    @Column(name="PYM_CHQNO")
    public Integer getPymChqno() {
        return this.pymChqno;
    }
    
    public void setPymChqno(Integer pymChqno) {
        this.pymChqno = pymChqno;
    }

    
    @Column(name="PYM_CHQDATE", length=50)
    public String getPymChqdate() {
        return this.pymChqdate;
    }
    
    public void setPymChqdate(String pymChqdate) {
        this.pymChqdate = pymChqdate;
    }




}


