package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PostMaster generated by hbm2java
 */
@Entity
@Table(name="post_master"
    ,catalog="e2rp"
)
public class PostMaster  implements java.io.Serializable {


     private Integer postId;
     private String postName;
     private String postIsactive;

    public PostMaster() {
    }

    public PostMaster(String postName, String postIsactive) {
       this.postName = postName;
       this.postIsactive = postIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="POST_ID", unique=true, nullable=false)
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    
    @Column(name="POST_NAME", nullable=false, length=50)
    public String getPostName() {
        return this.postName;
    }
    
    public void setPostName(String postName) {
        this.postName = postName;
    }

    
    @Column(name="POST_ISACTIVE", nullable=false, length=30)
    public String getPostIsactive() {
        return this.postIsactive;
    }
    
    public void setPostIsactive(String postIsactive) {
        this.postIsactive = postIsactive;
    }




}


