package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Receiptdetails generated by hbm2java
 */
@Entity
@Table(name="receiptdetails"
    ,catalog="e2rp"
)
public class Receiptdetails  implements java.io.Serializable {


     private ReceiptdetailsId id;
     private String recByorto;
     private String recNature;
     private String recParticulars;
     private int recAccId;
     private BigDecimal recDramount;
     private BigDecimal recCramount;

    public Receiptdetails() {
    }

	
    public Receiptdetails(ReceiptdetailsId id, String recByorto, String recNature, String recParticulars, int recAccId) {
        this.id = id;
        this.recByorto = recByorto;
        this.recNature = recNature;
        this.recParticulars = recParticulars;
        this.recAccId = recAccId;
    }
    public Receiptdetails(ReceiptdetailsId id, String recByorto, String recNature, String recParticulars, int recAccId, BigDecimal recDramount, BigDecimal recCramount) {
       this.id = id;
       this.recByorto = recByorto;
       this.recNature = recNature;
       this.recParticulars = recParticulars;
       this.recAccId = recAccId;
       this.recDramount = recDramount;
       this.recCramount = recCramount;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="recDtlid", column=@Column(name="REC_DTLID", nullable=false) ), 
        @AttributeOverride(name="recId", column=@Column(name="REC_ID", nullable=false) ) } )
    public ReceiptdetailsId getId() {
        return this.id;
    }
    
    public void setId(ReceiptdetailsId id) {
        this.id = id;
    }

    
    @Column(name="REC_BYORTO", nullable=false, length=20)
    public String getRecByorto() {
        return this.recByorto;
    }
    
    public void setRecByorto(String recByorto) {
        this.recByorto = recByorto;
    }

    
    @Column(name="REC_NATURE", nullable=false, length=50)
    public String getRecNature() {
        return this.recNature;
    }
    
    public void setRecNature(String recNature) {
        this.recNature = recNature;
    }

    
    @Column(name="REC_PARTICULARS", nullable=false, length=50)
    public String getRecParticulars() {
        return this.recParticulars;
    }
    
    public void setRecParticulars(String recParticulars) {
        this.recParticulars = recParticulars;
    }

    
    @Column(name="REC_ACC_ID", nullable=false)
    public int getRecAccId() {
        return this.recAccId;
    }
    
    public void setRecAccId(int recAccId) {
        this.recAccId = recAccId;
    }

    
    @Column(name="REC_DRAMOUNT", precision=18)
    public BigDecimal getRecDramount() {
        return this.recDramount;
    }
    
    public void setRecDramount(BigDecimal recDramount) {
        this.recDramount = recDramount;
    }

    
    @Column(name="REC_CRAMOUNT", precision=18)
    public BigDecimal getRecCramount() {
        return this.recCramount;
    }
    
    public void setRecCramount(BigDecimal recCramount) {
        this.recCramount = recCramount;
    }




}


