package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReceptionManageVisitors generated by hbm2java
 */
@Entity
@Table(name="reception_manage_visitors"
    ,catalog="e2rp"
)
public class ReceptionManageVisitors  implements java.io.Serializable {


     private Integer visitorId;
     private String visitorName;
     private String phoneNo;
     private String address;
     private int pinCode;
     private String visitorsQuery;
     private Date visitingDatetime;
     private int createdBy;
     private Date createdOn;
     private String visitorIsactive;

    public ReceptionManageVisitors() {
    }

    public ReceptionManageVisitors(String visitorName, String phoneNo, String address, int pinCode, String visitorsQuery, Date visitingDatetime, int createdBy, Date createdOn, String visitorIsactive) {
       this.visitorName = visitorName;
       this.phoneNo = phoneNo;
       this.address = address;
       this.pinCode = pinCode;
       this.visitorsQuery = visitorsQuery;
       this.visitingDatetime = visitingDatetime;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.visitorIsactive = visitorIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="VISITOR_ID", unique=true, nullable=false)
    public Integer getVisitorId() {
        return this.visitorId;
    }
    
    public void setVisitorId(Integer visitorId) {
        this.visitorId = visitorId;
    }

    
    @Column(name="VISITOR_NAME", nullable=false, length=100)
    public String getVisitorName() {
        return this.visitorName;
    }
    
    public void setVisitorName(String visitorName) {
        this.visitorName = visitorName;
    }

    
    @Column(name="PHONE_NO", nullable=false, length=20)
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    
    @Column(name="ADDRESS", nullable=false, length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="PIN_CODE", nullable=false)
    public int getPinCode() {
        return this.pinCode;
    }
    
    public void setPinCode(int pinCode) {
        this.pinCode = pinCode;
    }

    
    @Column(name="VISITORS_QUERY", nullable=false, length=250)
    public String getVisitorsQuery() {
        return this.visitorsQuery;
    }
    
    public void setVisitorsQuery(String visitorsQuery) {
        this.visitorsQuery = visitorsQuery;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VISITING_DATETIME", nullable=false, length=19)
    public Date getVisitingDatetime() {
        return this.visitingDatetime;
    }
    
    public void setVisitingDatetime(Date visitingDatetime) {
        this.visitingDatetime = visitingDatetime;
    }

    
    @Column(name="CREATED_BY", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_ON", nullable=false, length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="VISITOR_ISACTIVE", nullable=false, length=10)
    public String getVisitorIsactive() {
        return this.visitorIsactive;
    }
    
    public void setVisitorIsactive(String visitorIsactive) {
        this.visitorIsactive = visitorIsactive;
    }




}


