package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Receiptmaster generated by hbm2java
 */
@Entity
@Table(name="receiptmaster"
    ,catalog="e2rp"
)
public class Receiptmaster  implements java.io.Serializable {


     private Integer recId;
     private int recCodeid;
     private String recCode;
     private int recTocid;
     private Date recVoudate;
     private String recNarration;
     private String recType;
     private Integer recChqno;
     private String recChqdate;
     private Set<Receiptdetails> receiptdetailses = new HashSet<Receiptdetails>(0);

    public Receiptmaster() {
    }

	
    public Receiptmaster(int recCodeid, String recCode, int recTocid, Date recVoudate, String recNarration, String recType) {
        this.recCodeid = recCodeid;
        this.recCode = recCode;
        this.recTocid = recTocid;
        this.recVoudate = recVoudate;
        this.recNarration = recNarration;
        this.recType = recType;
    }
    public Receiptmaster(int recCodeid, String recCode, int recTocid, Date recVoudate, String recNarration, String recType, Integer recChqno, String recChqdate, Set<Receiptdetails> receiptdetailses) {
       this.recCodeid = recCodeid;
       this.recCode = recCode;
       this.recTocid = recTocid;
       this.recVoudate = recVoudate;
       this.recNarration = recNarration;
       this.recType = recType;
       this.recChqno = recChqno;
       this.recChqdate = recChqdate;
       this.receiptdetailses = receiptdetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="REC_ID", unique=true, nullable=false)
    public Integer getRecId() {
        return this.recId;
    }
    
    public void setRecId(Integer recId) {
        this.recId = recId;
    }

    
    @Column(name="REC_CODEID", nullable=false)
    public int getRecCodeid() {
        return this.recCodeid;
    }
    
    public void setRecCodeid(int recCodeid) {
        this.recCodeid = recCodeid;
    }

    
    @Column(name="REC_CODE", nullable=false, length=20)
    public String getRecCode() {
        return this.recCode;
    }
    
    public void setRecCode(String recCode) {
        this.recCode = recCode;
    }

    
    @Column(name="REC_TOCID", nullable=false)
    public int getRecTocid() {
        return this.recTocid;
    }
    
    public void setRecTocid(int recTocid) {
        this.recTocid = recTocid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REC_VOUDATE", nullable=false, length=19)
    public Date getRecVoudate() {
        return this.recVoudate;
    }
    
    public void setRecVoudate(Date recVoudate) {
        this.recVoudate = recVoudate;
    }

    
    @Column(name="REC_NARRATION", nullable=false)
    public String getRecNarration() {
        return this.recNarration;
    }
    
    public void setRecNarration(String recNarration) {
        this.recNarration = recNarration;
    }

    
    @Column(name="REC_TYPE", nullable=false, length=50)
    public String getRecType() {
        return this.recType;
    }
    
    public void setRecType(String recType) {
        this.recType = recType;
    }

    
    @Column(name="REC_CHQNO")
    public Integer getRecChqno() {
        return this.recChqno;
    }
    
    public void setRecChqno(Integer recChqno) {
        this.recChqno = recChqno;
    }

    
    @Column(name="REC_CHQDATE", length=50)
    public String getRecChqdate() {
        return this.recChqdate;
    }
    
    public void setRecChqdate(String recChqdate) {
        this.recChqdate = recChqdate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="receiptmaster")
    public Set<Receiptdetails> getReceiptdetailses() {
        return this.receiptdetailses;
    }
    
    public void setReceiptdetailses(Set<Receiptdetails> receiptdetailses) {
        this.receiptdetailses = receiptdetailses;
    }




}


