package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequsitionApproval generated by hbm2java
 */
@Entity
@Table(name="requsition_approval"
    ,catalog="e2rp"
)
public class RequsitionApproval  implements java.io.Serializable {


     private Integer reqAppId;
     private String requToId;
     private String requFromId;
     private int frwdReqId;
     private String appPrsnEmpId;
     private int reqAppCreatedby;
     private Date reqAppCreateddt;
     private String orderStatus;

    public RequsitionApproval() {
    }

    public RequsitionApproval(String requToId, String requFromId, int frwdReqId, String appPrsnEmpId, int reqAppCreatedby, Date reqAppCreateddt, String orderStatus) {
       this.requToId = requToId;
       this.requFromId = requFromId;
       this.frwdReqId = frwdReqId;
       this.appPrsnEmpId = appPrsnEmpId;
       this.reqAppCreatedby = reqAppCreatedby;
       this.reqAppCreateddt = reqAppCreateddt;
       this.orderStatus = orderStatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="REQ_APP_ID", unique=true, nullable=false)
    public Integer getReqAppId() {
        return this.reqAppId;
    }
    
    public void setReqAppId(Integer reqAppId) {
        this.reqAppId = reqAppId;
    }

    
    @Column(name="REQU_TO_ID", nullable=false, length=20)
    public String getRequToId() {
        return this.requToId;
    }
    
    public void setRequToId(String requToId) {
        this.requToId = requToId;
    }

    
    @Column(name="REQU_FROM_ID", nullable=false, length=100)
    public String getRequFromId() {
        return this.requFromId;
    }
    
    public void setRequFromId(String requFromId) {
        this.requFromId = requFromId;
    }

    
    @Column(name="FRWD_REQ_ID", nullable=false)
    public int getFrwdReqId() {
        return this.frwdReqId;
    }
    
    public void setFrwdReqId(int frwdReqId) {
        this.frwdReqId = frwdReqId;
    }

    
    @Column(name="APP_PRSN_EMP_ID", nullable=false, length=20)
    public String getAppPrsnEmpId() {
        return this.appPrsnEmpId;
    }
    
    public void setAppPrsnEmpId(String appPrsnEmpId) {
        this.appPrsnEmpId = appPrsnEmpId;
    }

    
    @Column(name="REQ_APP_CREATEDBY", nullable=false)
    public int getReqAppCreatedby() {
        return this.reqAppCreatedby;
    }
    
    public void setReqAppCreatedby(int reqAppCreatedby) {
        this.reqAppCreatedby = reqAppCreatedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REQ_APP_CREATEDDT", nullable=false, length=19)
    public Date getReqAppCreateddt() {
        return this.reqAppCreateddt;
    }
    
    public void setReqAppCreateddt(Date reqAppCreateddt) {
        this.reqAppCreateddt = reqAppCreateddt;
    }

    
    @Column(name="ORDER_STATUS", nullable=false, length=50)
    public String getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }




}


