package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RequsitionHistoryMaster generated by hbm2java
 */
@Entity
@Table(name="requsition_history_master"
    ,catalog="e2rp"
)
public class RequsitionHistoryMaster  implements java.io.Serializable {


     private Integer reqhistoryId;
     private int reqSlno;
     private String reqId;
     private int itemId;
     private BigDecimal quantity;
     private int vendorId;
     private String reference;
     private String reqStatus;
     private String flag;
     private int createdby;
     private Date createddt;
     private int editedby;
     private Date editeddt;

    public RequsitionHistoryMaster() {
    }

    public RequsitionHistoryMaster(int reqSlno, String reqId, int itemId, BigDecimal quantity, int vendorId, String reference, String reqStatus, String flag, int createdby, Date createddt, int editedby, Date editeddt) {
       this.reqSlno = reqSlno;
       this.reqId = reqId;
       this.itemId = itemId;
       this.quantity = quantity;
       this.vendorId = vendorId;
       this.reference = reference;
       this.reqStatus = reqStatus;
       this.flag = flag;
       this.createdby = createdby;
       this.createddt = createddt;
       this.editedby = editedby;
       this.editeddt = editeddt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="REQHISTORY_ID", unique=true, nullable=false)
    public Integer getReqhistoryId() {
        return this.reqhistoryId;
    }
    
    public void setReqhistoryId(Integer reqhistoryId) {
        this.reqhistoryId = reqhistoryId;
    }

    
    @Column(name="REQ_SLNO", nullable=false)
    public int getReqSlno() {
        return this.reqSlno;
    }
    
    public void setReqSlno(int reqSlno) {
        this.reqSlno = reqSlno;
    }

    
    @Column(name="REQ_ID", nullable=false, length=50)
    public String getReqId() {
        return this.reqId;
    }
    
    public void setReqId(String reqId) {
        this.reqId = reqId;
    }

    
    @Column(name="ITEM_ID", nullable=false)
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    
    @Column(name="QUANTITY", nullable=false, precision=18)
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="VENDOR_ID", nullable=false)
    public int getVendorId() {
        return this.vendorId;
    }
    
    public void setVendorId(int vendorId) {
        this.vendorId = vendorId;
    }

    
    @Column(name="REFERENCE", nullable=false, length=50)
    public String getReference() {
        return this.reference;
    }
    
    public void setReference(String reference) {
        this.reference = reference;
    }

    
    @Column(name="REQ_STATUS", nullable=false, length=50)
    public String getReqStatus() {
        return this.reqStatus;
    }
    
    public void setReqStatus(String reqStatus) {
        this.reqStatus = reqStatus;
    }

    
    @Column(name="FLAG", nullable=false)
    public String getFlag() {
        return this.flag;
    }
    
    public void setFlag(String flag) {
        this.flag = flag;
    }

    
    @Column(name="CREATEDBY", nullable=false)
    public int getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(int createdby) {
        this.createdby = createdby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATEDDT", nullable=false, length=19)
    public Date getCreateddt() {
        return this.createddt;
    }
    
    public void setCreateddt(Date createddt) {
        this.createddt = createddt;
    }

    
    @Column(name="EDITEDBY", nullable=false)
    public int getEditedby() {
        return this.editedby;
    }
    
    public void setEditedby(int editedby) {
        this.editedby = editedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EDITEDDT", nullable=false, length=19)
    public Date getEditeddt() {
        return this.editeddt;
    }
    
    public void setEditeddt(Date editeddt) {
        this.editeddt = editeddt;
    }




}


