package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RoomMaster generated by hbm2java
 */
@Entity
@Table(name="room_master"
    ,catalog="e2rp"
)
public class RoomMaster  implements java.io.Serializable {


     private Integer roomId;
     private String roomName;
     private int floorId;
     private String flag1;
     private String flag2;
     private String flag3;
     private String roomIsactive;

    public RoomMaster() {
    }

    public RoomMaster(String roomName, int floorId, String flag1, String flag2, String flag3, String roomIsactive) {
       this.roomName = roomName;
       this.floorId = floorId;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.roomIsactive = roomIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ROOM_ID", unique=true, nullable=false)
    public Integer getRoomId() {
        return this.roomId;
    }
    
    public void setRoomId(Integer roomId) {
        this.roomId = roomId;
    }

    
    @Column(name="ROOM_NAME", nullable=false, length=50)
    public String getRoomName() {
        return this.roomName;
    }
    
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    
    @Column(name="FLOOR_ID", nullable=false)
    public int getFloorId() {
        return this.floorId;
    }
    
    public void setFloorId(int floorId) {
        this.floorId = floorId;
    }

    
    @Column(name="FLAG_1", nullable=false, length=50)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", nullable=false, length=50)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", nullable=false, length=50)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="ROOM_ISACTIVE", nullable=false, length=10)
    public String getRoomIsactive() {
        return this.roomIsactive;
    }
    
    public void setRoomIsactive(String roomIsactive) {
        this.roomIsactive = roomIsactive;
    }




}


