package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SalaryMaster generated by hbm2java
 */
@Entity
@Table(name="salary_master"
    ,catalog="e2rp"
)
public class SalaryMaster  implements java.io.Serializable {


     private Integer salaryId;
     private int employeeId;
     private int designationId;
     private String basic;
     private String hra;
     private String da;
     private String pf;
     private String conveyance;
     private int flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private String salaryIsactive;

    public SalaryMaster() {
    }

    public SalaryMaster(int employeeId, int designationId, String basic, String hra, String da, String pf, String conveyance, int flag1, String flag2, String flag3, String flag4, String flag5, String salaryIsactive) {
       this.employeeId = employeeId;
       this.designationId = designationId;
       this.basic = basic;
       this.hra = hra;
       this.da = da;
       this.pf = pf;
       this.conveyance = conveyance;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.salaryIsactive = salaryIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SALARY_ID", unique=true, nullable=false)
    public Integer getSalaryId() {
        return this.salaryId;
    }
    
    public void setSalaryId(Integer salaryId) {
        this.salaryId = salaryId;
    }

    
    @Column(name="EMPLOYEE_ID", nullable=false)
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="DESIGNATION_ID", nullable=false)
    public int getDesignationId() {
        return this.designationId;
    }
    
    public void setDesignationId(int designationId) {
        this.designationId = designationId;
    }

    
    @Column(name="BASIC", nullable=false, length=50)
    public String getBasic() {
        return this.basic;
    }
    
    public void setBasic(String basic) {
        this.basic = basic;
    }

    
    @Column(name="HRA", nullable=false, length=50)
    public String getHra() {
        return this.hra;
    }
    
    public void setHra(String hra) {
        this.hra = hra;
    }

    
    @Column(name="DA", nullable=false, length=50)
    public String getDa() {
        return this.da;
    }
    
    public void setDa(String da) {
        this.da = da;
    }

    
    @Column(name="PF", nullable=false, length=50)
    public String getPf() {
        return this.pf;
    }
    
    public void setPf(String pf) {
        this.pf = pf;
    }

    
    @Column(name="CONVEYANCE", nullable=false, length=50)
    public String getConveyance() {
        return this.conveyance;
    }
    
    public void setConveyance(String conveyance) {
        this.conveyance = conveyance;
    }

    
    @Column(name="FLAG_1", nullable=false)
    public int getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(int flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", nullable=false, length=50)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", nullable=false, length=50)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="FLAG_4", nullable=false, length=50)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }

    
    @Column(name="FLAG_5", nullable=false, length=50)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }

    
    @Column(name="SALARY_ISACTIVE", nullable=false, length=10)
    public String getSalaryIsactive() {
        return this.salaryIsactive;
    }
    
    public void setSalaryIsactive(String salaryIsactive) {
        this.salaryIsactive = salaryIsactive;
    }




}


