package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StaffRegistration generated by hbm2java
 */
@Entity
@Table(name="staff_registration"
    ,catalog="e2rp"
)
public class StaffRegistration  implements java.io.Serializable {


     private Integer slid;
     private String regid;
     private String staffname;
     private Date dob;
     private int age;
     private String gender;
     private String fathersname;
     private String mothersname;
     private String email;
     private String mobileno;
     private String skill;
     private long graduationmarks;
     private String qualification;
     private String currentemployment;
     private String experience;
     private String address;
     private String city;
     private String state;
     private int pincode;
     private String medicalhistory;
     private String document;
     private String photo;
     private String flag3;
     private String flag4;
     private String flag5;
     private String enqIsactive;
     private String designation;
     private Integer column30;
     private Integer column31;

    public StaffRegistration() {
    }

	
    public StaffRegistration(String regid, String staffname, Date dob, int age, String gender, String fathersname, String mothersname, String email, String mobileno, String skill, long graduationmarks, String qualification, String currentemployment, String experience, String address, String city, String state, int pincode, String medicalhistory, String document, String photo, String flag3, String flag4, String flag5, String enqIsactive) {
        this.regid = regid;
        this.staffname = staffname;
        this.dob = dob;
        this.age = age;
        this.gender = gender;
        this.fathersname = fathersname;
        this.mothersname = mothersname;
        this.email = email;
        this.mobileno = mobileno;
        this.skill = skill;
        this.graduationmarks = graduationmarks;
        this.qualification = qualification;
        this.currentemployment = currentemployment;
        this.experience = experience;
        this.address = address;
        this.city = city;
        this.state = state;
        this.pincode = pincode;
        this.medicalhistory = medicalhistory;
        this.document = document;
        this.photo = photo;
        this.flag3 = flag3;
        this.flag4 = flag4;
        this.flag5 = flag5;
        this.enqIsactive = enqIsactive;
    }
    public StaffRegistration(String regid, String staffname, Date dob, int age, String gender, String fathersname, String mothersname, String email, String mobileno, String skill, long graduationmarks, String qualification, String currentemployment, String experience, String address, String city, String state, int pincode, String medicalhistory, String document, String photo, String flag3, String flag4, String flag5, String enqIsactive, String designation, Integer column30, Integer column31) {
       this.regid = regid;
       this.staffname = staffname;
       this.dob = dob;
       this.age = age;
       this.gender = gender;
       this.fathersname = fathersname;
       this.mothersname = mothersname;
       this.email = email;
       this.mobileno = mobileno;
       this.skill = skill;
       this.graduationmarks = graduationmarks;
       this.qualification = qualification;
       this.currentemployment = currentemployment;
       this.experience = experience;
       this.address = address;
       this.city = city;
       this.state = state;
       this.pincode = pincode;
       this.medicalhistory = medicalhistory;
       this.document = document;
       this.photo = photo;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.enqIsactive = enqIsactive;
       this.designation = designation;
       this.column30 = column30;
       this.column31 = column31;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SLID", unique=true, nullable=false)
    public Integer getSlid() {
        return this.slid;
    }
    
    public void setSlid(Integer slid) {
        this.slid = slid;
    }

    
    @Column(name="REGID", nullable=false, length=50)
    public String getRegid() {
        return this.regid;
    }
    
    public void setRegid(String regid) {
        this.regid = regid;
    }

    
    @Column(name="STAFFNAME", nullable=false, length=50)
    public String getStaffname() {
        return this.staffname;
    }
    
    public void setStaffname(String staffname) {
        this.staffname = staffname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="DOB", nullable=false, length=19)
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }

    
    @Column(name="AGE", nullable=false)
    public int getAge() {
        return this.age;
    }
    
    public void setAge(int age) {
        this.age = age;
    }

    
    @Column(name="GENDER", nullable=false, length=10)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="FATHERSNAME", nullable=false, length=50)
    public String getFathersname() {
        return this.fathersname;
    }
    
    public void setFathersname(String fathersname) {
        this.fathersname = fathersname;
    }

    
    @Column(name="MOTHERSNAME", nullable=false, length=50)
    public String getMothersname() {
        return this.mothersname;
    }
    
    public void setMothersname(String mothersname) {
        this.mothersname = mothersname;
    }

    
    @Column(name="EMAIL", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="MOBILENO", nullable=false, length=15)
    public String getMobileno() {
        return this.mobileno;
    }
    
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }

    
    @Column(name="SKILL", nullable=false, length=250)
    public String getSkill() {
        return this.skill;
    }
    
    public void setSkill(String skill) {
        this.skill = skill;
    }

    
    @Column(name="GRADUATIONMARKS", nullable=false, precision=18, scale=0)
    public long getGraduationmarks() {
        return this.graduationmarks;
    }
    
    public void setGraduationmarks(long graduationmarks) {
        this.graduationmarks = graduationmarks;
    }

    
    @Column(name="QUALIFICATION", nullable=false, length=250)
    public String getQualification() {
        return this.qualification;
    }
    
    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

    
    @Column(name="CURRENTEMPLOYMENT", nullable=false, length=20)
    public String getCurrentemployment() {
        return this.currentemployment;
    }
    
    public void setCurrentemployment(String currentemployment) {
        this.currentemployment = currentemployment;
    }

    
    @Column(name="EXPERIENCE", nullable=false, length=20)
    public String getExperience() {
        return this.experience;
    }
    
    public void setExperience(String experience) {
        this.experience = experience;
    }

    
    @Column(name="ADDRESS", nullable=false, length=250)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="CITY", nullable=false, length=30)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="STATE", nullable=false, length=30)
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    @Column(name="PINCODE", nullable=false)
    public int getPincode() {
        return this.pincode;
    }
    
    public void setPincode(int pincode) {
        this.pincode = pincode;
    }

    
    @Column(name="MEDICALHISTORY", nullable=false, length=30)
    public String getMedicalhistory() {
        return this.medicalhistory;
    }
    
    public void setMedicalhistory(String medicalhistory) {
        this.medicalhistory = medicalhistory;
    }

    
    @Column(name="DOCUMENT", nullable=false, length=30)
    public String getDocument() {
        return this.document;
    }
    
    public void setDocument(String document) {
        this.document = document;
    }

    
    @Column(name="PHOTO", nullable=false, length=30)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="FLAG_3", nullable=false, length=30)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="FLAG_4", nullable=false, length=30)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }

    
    @Column(name="FLAG_5", nullable=false, length=30)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }

    
    @Column(name="ENQ_ISACTIVE", nullable=false, length=30)
    public String getEnqIsactive() {
        return this.enqIsactive;
    }
    
    public void setEnqIsactive(String enqIsactive) {
        this.enqIsactive = enqIsactive;
    }

    
    @Column(name="DESIGNATION", length=50)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="Column_30")
    public Integer getColumn30() {
        return this.column30;
    }
    
    public void setColumn30(Integer column30) {
        this.column30 = column30;
    }

    
    @Column(name="Column_31")
    public Integer getColumn31() {
        return this.column31;
    }
    
    public void setColumn31(Integer column31) {
        this.column31 = column31;
    }




}


