package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StaffDetails generated by hbm2java
 */
@Entity
@Table(name="staff_details"
    ,catalog="e2rp"
)
public class StaffDetails  implements java.io.Serializable {


     private Integer salaryId;
     private int employeeId;
     private int designationId;
     private BigDecimal basic;
     private BigDecimal hra;
     private BigDecimal da;
     private BigDecimal conveyance;
     private BigDecimal otherallowences;
     private String totalLeave;
     private int flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private String salaryIsactive;

    public StaffDetails() {
    }

    public StaffDetails(int employeeId, int designationId, BigDecimal basic, BigDecimal hra, BigDecimal da, BigDecimal conveyance, BigDecimal otherallowences, String totalLeave, int flag1, String flag2, String flag3, String flag4, String flag5, String salaryIsactive) {
       this.employeeId = employeeId;
       this.designationId = designationId;
       this.basic = basic;
       this.hra = hra;
       this.da = da;
       this.conveyance = conveyance;
       this.otherallowences = otherallowences;
       this.totalLeave = totalLeave;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.salaryIsactive = salaryIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SALARY_ID", unique=true, nullable=false)
    public Integer getSalaryId() {
        return this.salaryId;
    }
    
    public void setSalaryId(Integer salaryId) {
        this.salaryId = salaryId;
    }

    
    @Column(name="EMPLOYEE_ID", nullable=false)
    public int getEmployeeId() {
        return this.employeeId;
    }
    
    public void setEmployeeId(int employeeId) {
        this.employeeId = employeeId;
    }

    
    @Column(name="DESIGNATION_ID", nullable=false)
    public int getDesignationId() {
        return this.designationId;
    }
    
    public void setDesignationId(int designationId) {
        this.designationId = designationId;
    }

    
    @Column(name="BASIC", nullable=false, precision=7)
    public BigDecimal getBasic() {
        return this.basic;
    }
    
    public void setBasic(BigDecimal basic) {
        this.basic = basic;
    }

    
    @Column(name="HRA", nullable=false, precision=7)
    public BigDecimal getHra() {
        return this.hra;
    }
    
    public void setHra(BigDecimal hra) {
        this.hra = hra;
    }

    
    @Column(name="DA", nullable=false, precision=7)
    public BigDecimal getDa() {
        return this.da;
    }
    
    public void setDa(BigDecimal da) {
        this.da = da;
    }

    
    @Column(name="CONVEYANCE", nullable=false, precision=7)
    public BigDecimal getConveyance() {
        return this.conveyance;
    }
    
    public void setConveyance(BigDecimal conveyance) {
        this.conveyance = conveyance;
    }

    
    @Column(name="OTHERALLOWENCES", nullable=false, precision=7)
    public BigDecimal getOtherallowences() {
        return this.otherallowences;
    }
    
    public void setOtherallowences(BigDecimal otherallowences) {
        this.otherallowences = otherallowences;
    }

    
    @Column(name="TOTAL_LEAVE", nullable=false, length=50)
    public String getTotalLeave() {
        return this.totalLeave;
    }
    
    public void setTotalLeave(String totalLeave) {
        this.totalLeave = totalLeave;
    }

    
    @Column(name="FLAG_1", nullable=false)
    public int getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(int flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", nullable=false, length=50)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", nullable=false, length=50)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="FLAG_4", nullable=false, length=50)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }

    
    @Column(name="FLAG_5", nullable=false, length=50)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }

    
    @Column(name="SALARY_ISACTIVE", nullable=false, length=10)
    public String getSalaryIsactive() {
        return this.salaryIsactive;
    }
    
    public void setSalaryIsactive(String salaryIsactive) {
        this.salaryIsactive = salaryIsactive;
    }




}


