package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StateMaster generated by hbm2java
 */
@Entity
@Table(name="state_master"
    ,catalog="e2rp"
)
public class StateMaster  implements java.io.Serializable {


     private Integer stateId;
     private String stateName;
     private String countryCode;

    public StateMaster() {
    }

    public StateMaster(String stateName, String countryCode) {
       this.stateName = stateName;
       this.countryCode = countryCode;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STATE_ID", unique=true, nullable=false)
    public Integer getStateId() {
        return this.stateId;
    }
    
    public void setStateId(Integer stateId) {
        this.stateId = stateId;
    }

    
    @Column(name="STATE_NAME", nullable=false, length=50)
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }

    
    @Column(name="COUNTRY_CODE", nullable=false, length=50)
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }




}


