package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Studentmaster generated by hbm2java
 */
@Entity
@Table(name="studentmaster"
    ,catalog="e2rp"
)
public class Studentmaster  implements java.io.Serializable {


     private Integer stuSeriId;
     private String stuAdmissionno;
     private String stuStudentid;
     private String stuRegistrationid;
     private Date stuAdmissiondate;
     private int stuAdmissionstatus;
     private String stuStudentname;
     private Date stuDob;
     private String stuGender;
     private int stuAge;
     private String stuBloodgroup;
     private BigDecimal stuPreviousmarks;
     private String stuAddressline;
     private String stuState;
     private String stuCity;
     private int stuPincode;
     private int stuNoofsiblings;
     private String stuNatinality;
     private String stuReligion;
     private int stuPicture;
     private String stuPhysicallychallenged;
     private String stuChallengetype;
     private String stuFathername;
     private String stuFathermobile;
     private String stuFatheroccupation;
     private String stuFatherqualification;
     private String stuFatheremail;
     private String stuMothername;
     private String stuMothermobile;
     private String stuMotheroccupation;
     private String stuMotherqualification;
     private String stuMotheremail;
     private BigDecimal stuFamilyincome;
     private Date stuMarriagedate;
     private String stuGuardianname;
     private String stuGurdianoccupation;
     private String stuRelatiowithstudent;
     private String stuGuardianmobile;
     private String stuGuardianemail;
     private String stuSchoolname;
     private String stuSchooladdress;
     private String stuSchoolphone;
     private String stuSchoolwebsite;
     private String stuSchoolemail;
     private int stuAdmissionyear;
     private String stuIdentificationmark;
     private String stuRationcard;
     private String stuBirthcertificate;
     private String stuDisease;
     private int stuCurrentstatus;
     private int stuFlag2;
     private String stuFlag3;
     private String stuFlag4;
     private String stuFlag5;
     private int stuCreatedby;
     private Date stuCreatedon;
     private int stuEditedby;
     private Date stuEditedon;
     private String stuIsactive;

    public Studentmaster() {
    }

    public Studentmaster(String stuAdmissionno, String stuStudentid, String stuRegistrationid, Date stuAdmissiondate, int stuAdmissionstatus, String stuStudentname, Date stuDob, String stuGender, int stuAge, String stuBloodgroup, BigDecimal stuPreviousmarks, String stuAddressline, String stuState, String stuCity, int stuPincode, int stuNoofsiblings, String stuNatinality, String stuReligion, int stuPicture, String stuPhysicallychallenged, String stuChallengetype, String stuFathername, String stuFathermobile, String stuFatheroccupation, String stuFatherqualification, String stuFatheremail, String stuMothername, String stuMothermobile, String stuMotheroccupation, String stuMotherqualification, String stuMotheremail, BigDecimal stuFamilyincome, Date stuMarriagedate, String stuGuardianname, String stuGurdianoccupation, String stuRelatiowithstudent, String stuGuardianmobile, String stuGuardianemail, String stuSchoolname, String stuSchooladdress, String stuSchoolphone, String stuSchoolwebsite, String stuSchoolemail, int stuAdmissionyear, String stuIdentificationmark, String stuRationcard, String stuBirthcertificate, String stuDisease, int stuCurrentstatus, int stuFlag2, String stuFlag3, String stuFlag4, String stuFlag5, int stuCreatedby, Date stuCreatedon, int stuEditedby, Date stuEditedon, String stuIsactive) {
       this.stuAdmissionno = stuAdmissionno;
       this.stuStudentid = stuStudentid;
       this.stuRegistrationid = stuRegistrationid;
       this.stuAdmissiondate = stuAdmissiondate;
       this.stuAdmissionstatus = stuAdmissionstatus;
       this.stuStudentname = stuStudentname;
       this.stuDob = stuDob;
       this.stuGender = stuGender;
       this.stuAge = stuAge;
       this.stuBloodgroup = stuBloodgroup;
       this.stuPreviousmarks = stuPreviousmarks;
       this.stuAddressline = stuAddressline;
       this.stuState = stuState;
       this.stuCity = stuCity;
       this.stuPincode = stuPincode;
       this.stuNoofsiblings = stuNoofsiblings;
       this.stuNatinality = stuNatinality;
       this.stuReligion = stuReligion;
       this.stuPicture = stuPicture;
       this.stuPhysicallychallenged = stuPhysicallychallenged;
       this.stuChallengetype = stuChallengetype;
       this.stuFathername = stuFathername;
       this.stuFathermobile = stuFathermobile;
       this.stuFatheroccupation = stuFatheroccupation;
       this.stuFatherqualification = stuFatherqualification;
       this.stuFatheremail = stuFatheremail;
       this.stuMothername = stuMothername;
       this.stuMothermobile = stuMothermobile;
       this.stuMotheroccupation = stuMotheroccupation;
       this.stuMotherqualification = stuMotherqualification;
       this.stuMotheremail = stuMotheremail;
       this.stuFamilyincome = stuFamilyincome;
       this.stuMarriagedate = stuMarriagedate;
       this.stuGuardianname = stuGuardianname;
       this.stuGurdianoccupation = stuGurdianoccupation;
       this.stuRelatiowithstudent = stuRelatiowithstudent;
       this.stuGuardianmobile = stuGuardianmobile;
       this.stuGuardianemail = stuGuardianemail;
       this.stuSchoolname = stuSchoolname;
       this.stuSchooladdress = stuSchooladdress;
       this.stuSchoolphone = stuSchoolphone;
       this.stuSchoolwebsite = stuSchoolwebsite;
       this.stuSchoolemail = stuSchoolemail;
       this.stuAdmissionyear = stuAdmissionyear;
       this.stuIdentificationmark = stuIdentificationmark;
       this.stuRationcard = stuRationcard;
       this.stuBirthcertificate = stuBirthcertificate;
       this.stuDisease = stuDisease;
       this.stuCurrentstatus = stuCurrentstatus;
       this.stuFlag2 = stuFlag2;
       this.stuFlag3 = stuFlag3;
       this.stuFlag4 = stuFlag4;
       this.stuFlag5 = stuFlag5;
       this.stuCreatedby = stuCreatedby;
       this.stuCreatedon = stuCreatedon;
       this.stuEditedby = stuEditedby;
       this.stuEditedon = stuEditedon;
       this.stuIsactive = stuIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STU_SERI_ID", unique=true, nullable=false)
    public Integer getStuSeriId() {
        return this.stuSeriId;
    }
    
    public void setStuSeriId(Integer stuSeriId) {
        this.stuSeriId = stuSeriId;
    }

    
    @Column(name="STU_ADMISSIONNO", nullable=false, length=50)
    public String getStuAdmissionno() {
        return this.stuAdmissionno;
    }
    
    public void setStuAdmissionno(String stuAdmissionno) {
        this.stuAdmissionno = stuAdmissionno;
    }

    
    @Column(name="STU_STUDENTID", nullable=false, length=50)
    public String getStuStudentid() {
        return this.stuStudentid;
    }
    
    public void setStuStudentid(String stuStudentid) {
        this.stuStudentid = stuStudentid;
    }

    
    @Column(name="STU_REGISTRATIONID", nullable=false, length=50)
    public String getStuRegistrationid() {
        return this.stuRegistrationid;
    }
    
    public void setStuRegistrationid(String stuRegistrationid) {
        this.stuRegistrationid = stuRegistrationid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STU_ADMISSIONDATE", nullable=false, length=19)
    public Date getStuAdmissiondate() {
        return this.stuAdmissiondate;
    }
    
    public void setStuAdmissiondate(Date stuAdmissiondate) {
        this.stuAdmissiondate = stuAdmissiondate;
    }

    
    @Column(name="STU_ADMISSIONSTATUS", nullable=false)
    public int getStuAdmissionstatus() {
        return this.stuAdmissionstatus;
    }
    
    public void setStuAdmissionstatus(int stuAdmissionstatus) {
        this.stuAdmissionstatus = stuAdmissionstatus;
    }

    
    @Column(name="STU_STUDENTNAME", nullable=false, length=50)
    public String getStuStudentname() {
        return this.stuStudentname;
    }
    
    public void setStuStudentname(String stuStudentname) {
        this.stuStudentname = stuStudentname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STU_DOB", nullable=false, length=19)
    public Date getStuDob() {
        return this.stuDob;
    }
    
    public void setStuDob(Date stuDob) {
        this.stuDob = stuDob;
    }

    
    @Column(name="STU_GENDER", nullable=false, length=50)
    public String getStuGender() {
        return this.stuGender;
    }
    
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender;
    }

    
    @Column(name="STU_AGE", nullable=false)
    public int getStuAge() {
        return this.stuAge;
    }
    
    public void setStuAge(int stuAge) {
        this.stuAge = stuAge;
    }

    
    @Column(name="STU_BLOODGROUP", nullable=false, length=50)
    public String getStuBloodgroup() {
        return this.stuBloodgroup;
    }
    
    public void setStuBloodgroup(String stuBloodgroup) {
        this.stuBloodgroup = stuBloodgroup;
    }

    
    @Column(name="STU_PREVIOUSMARKS", nullable=false, precision=18)
    public BigDecimal getStuPreviousmarks() {
        return this.stuPreviousmarks;
    }
    
    public void setStuPreviousmarks(BigDecimal stuPreviousmarks) {
        this.stuPreviousmarks = stuPreviousmarks;
    }

    
    @Column(name="STU_ADDRESSLINE", nullable=false, length=250)
    public String getStuAddressline() {
        return this.stuAddressline;
    }
    
    public void setStuAddressline(String stuAddressline) {
        this.stuAddressline = stuAddressline;
    }

    
    @Column(name="STU_STATE", nullable=false, length=50)
    public String getStuState() {
        return this.stuState;
    }
    
    public void setStuState(String stuState) {
        this.stuState = stuState;
    }

    
    @Column(name="STU_CITY", nullable=false, length=50)
    public String getStuCity() {
        return this.stuCity;
    }
    
    public void setStuCity(String stuCity) {
        this.stuCity = stuCity;
    }

    
    @Column(name="STU_PINCODE", nullable=false)
    public int getStuPincode() {
        return this.stuPincode;
    }
    
    public void setStuPincode(int stuPincode) {
        this.stuPincode = stuPincode;
    }

    
    @Column(name="STU_NOOFSIBLINGS", nullable=false)
    public int getStuNoofsiblings() {
        return this.stuNoofsiblings;
    }
    
    public void setStuNoofsiblings(int stuNoofsiblings) {
        this.stuNoofsiblings = stuNoofsiblings;
    }

    
    @Column(name="STU_NATINALITY", nullable=false, length=50)
    public String getStuNatinality() {
        return this.stuNatinality;
    }
    
    public void setStuNatinality(String stuNatinality) {
        this.stuNatinality = stuNatinality;
    }

    
    @Column(name="STU_RELIGION", nullable=false, length=50)
    public String getStuReligion() {
        return this.stuReligion;
    }
    
    public void setStuReligion(String stuReligion) {
        this.stuReligion = stuReligion;
    }

    
    @Column(name="STU_PICTURE", nullable=false)
    public int getStuPicture() {
        return this.stuPicture;
    }
    
    public void setStuPicture(int stuPicture) {
        this.stuPicture = stuPicture;
    }

    
    @Column(name="STU_PHYSICALLYCHALLENGED", nullable=false, length=10)
    public String getStuPhysicallychallenged() {
        return this.stuPhysicallychallenged;
    }
    
    public void setStuPhysicallychallenged(String stuPhysicallychallenged) {
        this.stuPhysicallychallenged = stuPhysicallychallenged;
    }

    
    @Column(name="STU_CHALLENGETYPE", nullable=false, length=50)
    public String getStuChallengetype() {
        return this.stuChallengetype;
    }
    
    public void setStuChallengetype(String stuChallengetype) {
        this.stuChallengetype = stuChallengetype;
    }

    
    @Column(name="STU_FATHERNAME", nullable=false, length=50)
    public String getStuFathername() {
        return this.stuFathername;
    }
    
    public void setStuFathername(String stuFathername) {
        this.stuFathername = stuFathername;
    }

    
    @Column(name="STU_FATHERMOBILE", nullable=false, length=50)
    public String getStuFathermobile() {
        return this.stuFathermobile;
    }
    
    public void setStuFathermobile(String stuFathermobile) {
        this.stuFathermobile = stuFathermobile;
    }

    
    @Column(name="STU_FATHEROCCUPATION", nullable=false, length=50)
    public String getStuFatheroccupation() {
        return this.stuFatheroccupation;
    }
    
    public void setStuFatheroccupation(String stuFatheroccupation) {
        this.stuFatheroccupation = stuFatheroccupation;
    }

    
    @Column(name="STU_FATHERQUALIFICATION", nullable=false, length=50)
    public String getStuFatherqualification() {
        return this.stuFatherqualification;
    }
    
    public void setStuFatherqualification(String stuFatherqualification) {
        this.stuFatherqualification = stuFatherqualification;
    }

    
    @Column(name="STU_FATHEREMAIL", nullable=false, length=50)
    public String getStuFatheremail() {
        return this.stuFatheremail;
    }
    
    public void setStuFatheremail(String stuFatheremail) {
        this.stuFatheremail = stuFatheremail;
    }

    
    @Column(name="STU_MOTHERNAME", nullable=false, length=50)
    public String getStuMothername() {
        return this.stuMothername;
    }
    
    public void setStuMothername(String stuMothername) {
        this.stuMothername = stuMothername;
    }

    
    @Column(name="STU_MOTHERMOBILE", nullable=false, length=50)
    public String getStuMothermobile() {
        return this.stuMothermobile;
    }
    
    public void setStuMothermobile(String stuMothermobile) {
        this.stuMothermobile = stuMothermobile;
    }

    
    @Column(name="STU_MOTHEROCCUPATION", nullable=false, length=50)
    public String getStuMotheroccupation() {
        return this.stuMotheroccupation;
    }
    
    public void setStuMotheroccupation(String stuMotheroccupation) {
        this.stuMotheroccupation = stuMotheroccupation;
    }

    
    @Column(name="STU_MOTHERQUALIFICATION", nullable=false, length=50)
    public String getStuMotherqualification() {
        return this.stuMotherqualification;
    }
    
    public void setStuMotherqualification(String stuMotherqualification) {
        this.stuMotherqualification = stuMotherqualification;
    }

    
    @Column(name="STU_MOTHEREMAIL", nullable=false, length=50)
    public String getStuMotheremail() {
        return this.stuMotheremail;
    }
    
    public void setStuMotheremail(String stuMotheremail) {
        this.stuMotheremail = stuMotheremail;
    }

    
    @Column(name="STU_FAMILYINCOME", nullable=false, precision=18)
    public BigDecimal getStuFamilyincome() {
        return this.stuFamilyincome;
    }
    
    public void setStuFamilyincome(BigDecimal stuFamilyincome) {
        this.stuFamilyincome = stuFamilyincome;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STU_MARRIAGEDATE", nullable=false, length=19)
    public Date getStuMarriagedate() {
        return this.stuMarriagedate;
    }
    
    public void setStuMarriagedate(Date stuMarriagedate) {
        this.stuMarriagedate = stuMarriagedate;
    }

    
    @Column(name="STU_GUARDIANNAME", nullable=false, length=50)
    public String getStuGuardianname() {
        return this.stuGuardianname;
    }
    
    public void setStuGuardianname(String stuGuardianname) {
        this.stuGuardianname = stuGuardianname;
    }

    
    @Column(name="STU_GURDIANOCCUPATION", nullable=false, length=50)
    public String getStuGurdianoccupation() {
        return this.stuGurdianoccupation;
    }
    
    public void setStuGurdianoccupation(String stuGurdianoccupation) {
        this.stuGurdianoccupation = stuGurdianoccupation;
    }

    
    @Column(name="STU_RELATIOWITHSTUDENT", nullable=false, length=50)
    public String getStuRelatiowithstudent() {
        return this.stuRelatiowithstudent;
    }
    
    public void setStuRelatiowithstudent(String stuRelatiowithstudent) {
        this.stuRelatiowithstudent = stuRelatiowithstudent;
    }

    
    @Column(name="STU_GUARDIANMOBILE", nullable=false, length=50)
    public String getStuGuardianmobile() {
        return this.stuGuardianmobile;
    }
    
    public void setStuGuardianmobile(String stuGuardianmobile) {
        this.stuGuardianmobile = stuGuardianmobile;
    }

    
    @Column(name="STU_GUARDIANEMAIL", nullable=false, length=50)
    public String getStuGuardianemail() {
        return this.stuGuardianemail;
    }
    
    public void setStuGuardianemail(String stuGuardianemail) {
        this.stuGuardianemail = stuGuardianemail;
    }

    
    @Column(name="STU_SCHOOLNAME", nullable=false, length=50)
    public String getStuSchoolname() {
        return this.stuSchoolname;
    }
    
    public void setStuSchoolname(String stuSchoolname) {
        this.stuSchoolname = stuSchoolname;
    }

    
    @Column(name="STU_SCHOOLADDRESS", nullable=false, length=250)
    public String getStuSchooladdress() {
        return this.stuSchooladdress;
    }
    
    public void setStuSchooladdress(String stuSchooladdress) {
        this.stuSchooladdress = stuSchooladdress;
    }

    
    @Column(name="STU_SCHOOLPHONE", nullable=false, length=50)
    public String getStuSchoolphone() {
        return this.stuSchoolphone;
    }
    
    public void setStuSchoolphone(String stuSchoolphone) {
        this.stuSchoolphone = stuSchoolphone;
    }

    
    @Column(name="STU_SCHOOLWEBSITE", nullable=false, length=50)
    public String getStuSchoolwebsite() {
        return this.stuSchoolwebsite;
    }
    
    public void setStuSchoolwebsite(String stuSchoolwebsite) {
        this.stuSchoolwebsite = stuSchoolwebsite;
    }

    
    @Column(name="STU_SCHOOLEMAIL", nullable=false, length=50)
    public String getStuSchoolemail() {
        return this.stuSchoolemail;
    }
    
    public void setStuSchoolemail(String stuSchoolemail) {
        this.stuSchoolemail = stuSchoolemail;
    }

    
    @Column(name="STU_ADMISSIONYEAR", nullable=false)
    public int getStuAdmissionyear() {
        return this.stuAdmissionyear;
    }
    
    public void setStuAdmissionyear(int stuAdmissionyear) {
        this.stuAdmissionyear = stuAdmissionyear;
    }

    
    @Column(name="STU_IDENTIFICATIONMARK", nullable=false, length=50)
    public String getStuIdentificationmark() {
        return this.stuIdentificationmark;
    }
    
    public void setStuIdentificationmark(String stuIdentificationmark) {
        this.stuIdentificationmark = stuIdentificationmark;
    }

    
    @Column(name="STU_RATIONCARD", nullable=false, length=50)
    public String getStuRationcard() {
        return this.stuRationcard;
    }
    
    public void setStuRationcard(String stuRationcard) {
        this.stuRationcard = stuRationcard;
    }

    
    @Column(name="STU_BIRTHCERTIFICATE", nullable=false, length=50)
    public String getStuBirthcertificate() {
        return this.stuBirthcertificate;
    }
    
    public void setStuBirthcertificate(String stuBirthcertificate) {
        this.stuBirthcertificate = stuBirthcertificate;
    }

    
    @Column(name="STU_DISEASE", nullable=false, length=50)
    public String getStuDisease() {
        return this.stuDisease;
    }
    
    public void setStuDisease(String stuDisease) {
        this.stuDisease = stuDisease;
    }

    
    @Column(name="STU_CURRENTSTATUS", nullable=false)
    public int getStuCurrentstatus() {
        return this.stuCurrentstatus;
    }
    
    public void setStuCurrentstatus(int stuCurrentstatus) {
        this.stuCurrentstatus = stuCurrentstatus;
    }

    
    @Column(name="STU_FLAG_2", nullable=false)
    public int getStuFlag2() {
        return this.stuFlag2;
    }
    
    public void setStuFlag2(int stuFlag2) {
        this.stuFlag2 = stuFlag2;
    }

    
    @Column(name="STU_FLAG_3", nullable=false, length=50)
    public String getStuFlag3() {
        return this.stuFlag3;
    }
    
    public void setStuFlag3(String stuFlag3) {
        this.stuFlag3 = stuFlag3;
    }

    
    @Column(name="STU_FLAG_4", nullable=false, length=50)
    public String getStuFlag4() {
        return this.stuFlag4;
    }
    
    public void setStuFlag4(String stuFlag4) {
        this.stuFlag4 = stuFlag4;
    }

    
    @Column(name="STU_FLAG_5", nullable=false, length=50)
    public String getStuFlag5() {
        return this.stuFlag5;
    }
    
    public void setStuFlag5(String stuFlag5) {
        this.stuFlag5 = stuFlag5;
    }

    
    @Column(name="STU_CREATEDBY", nullable=false)
    public int getStuCreatedby() {
        return this.stuCreatedby;
    }
    
    public void setStuCreatedby(int stuCreatedby) {
        this.stuCreatedby = stuCreatedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STU_CREATEDON", nullable=false, length=19)
    public Date getStuCreatedon() {
        return this.stuCreatedon;
    }
    
    public void setStuCreatedon(Date stuCreatedon) {
        this.stuCreatedon = stuCreatedon;
    }

    
    @Column(name="STU_EDITEDBY", nullable=false)
    public int getStuEditedby() {
        return this.stuEditedby;
    }
    
    public void setStuEditedby(int stuEditedby) {
        this.stuEditedby = stuEditedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="STU_EDITEDON", nullable=false, length=19)
    public Date getStuEditedon() {
        return this.stuEditedon;
    }
    
    public void setStuEditedon(Date stuEditedon) {
        this.stuEditedon = stuEditedon;
    }

    
    @Column(name="STU_ISACTIVE", nullable=false, length=30)
    public String getStuIsactive() {
        return this.stuIsactive;
    }
    
    public void setStuIsactive(String stuIsactive) {
        this.stuIsactive = stuIsactive;
    }




}


