package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentRegistration generated by hbm2java
 */
@Entity
@Table(name="student_registration"
    ,catalog="e2rp"
)
public class StudentRegistration  implements java.io.Serializable {


     private String regid;
     private int slid;
     private String enqid;
     private String bloodgroup;
     private String physicallychallnged;
     private String challengetype;
     private String nationality;
     private String region;
     private String remark;
     private int picture;
     private Date regdate;
     private String admissionstatus;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private String enqIsactive;

    public StudentRegistration() {
    }

    public StudentRegistration(String regid, int slid, String enqid, String bloodgroup, String physicallychallnged, String challengetype, String nationality, String region, String remark, int picture, Date regdate, String admissionstatus, String flag1, String flag2, String flag3, String flag4, String flag5, String enqIsactive) {
       this.regid = regid;
       this.slid = slid;
       this.enqid = enqid;
       this.bloodgroup = bloodgroup;
       this.physicallychallnged = physicallychallnged;
       this.challengetype = challengetype;
       this.nationality = nationality;
       this.region = region;
       this.remark = remark;
       this.picture = picture;
       this.regdate = regdate;
       this.admissionstatus = admissionstatus;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.enqIsactive = enqIsactive;
    }
   
     @Id 

    
    @Column(name="REGID", unique=true, nullable=false, length=30)
    public String getRegid() {
        return this.regid;
    }
    
    public void setRegid(String regid) {
        this.regid = regid;
    }

    
    @Column(name="SLID", nullable=false)
    public int getSlid() {
        return this.slid;
    }
    
    public void setSlid(int slid) {
        this.slid = slid;
    }

    
    @Column(name="ENQID", nullable=false, length=30)
    public String getEnqid() {
        return this.enqid;
    }
    
    public void setEnqid(String enqid) {
        this.enqid = enqid;
    }

    
    @Column(name="BLOODGROUP", nullable=false, length=10)
    public String getBloodgroup() {
        return this.bloodgroup;
    }
    
    public void setBloodgroup(String bloodgroup) {
        this.bloodgroup = bloodgroup;
    }

    
    @Column(name="PHYSICALLYCHALLNGED", nullable=false, length=30)
    public String getPhysicallychallnged() {
        return this.physicallychallnged;
    }
    
    public void setPhysicallychallnged(String physicallychallnged) {
        this.physicallychallnged = physicallychallnged;
    }

    
    @Column(name="CHALLENGETYPE", nullable=false, length=30)
    public String getChallengetype() {
        return this.challengetype;
    }
    
    public void setChallengetype(String challengetype) {
        this.challengetype = challengetype;
    }

    
    @Column(name="NATIONALITY", nullable=false, length=30)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="REGION", nullable=false, length=30)
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }

    
    @Column(name="REMARK", nullable=false, length=30)
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }

    
    @Column(name="PICTURE", nullable=false)
    public int getPicture() {
        return this.picture;
    }
    
    public void setPicture(int picture) {
        this.picture = picture;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REGDATE", nullable=false, length=19)
    public Date getRegdate() {
        return this.regdate;
    }
    
    public void setRegdate(Date regdate) {
        this.regdate = regdate;
    }

    
    @Column(name="ADMISSIONSTATUS", nullable=false, length=30)
    public String getAdmissionstatus() {
        return this.admissionstatus;
    }
    
    public void setAdmissionstatus(String admissionstatus) {
        this.admissionstatus = admissionstatus;
    }

    
    @Column(name="FLAG_1", nullable=false, length=30)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", nullable=false, length=30)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", nullable=false, length=30)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="FLAG_4", nullable=false, length=30)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }

    
    @Column(name="FLAG_5", nullable=false, length=30)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }

    
    @Column(name="ENQ_ISACTIVE", nullable=false, length=30)
    public String getEnqIsactive() {
        return this.enqIsactive;
    }
    
    public void setEnqIsactive(String enqIsactive) {
        this.enqIsactive = enqIsactive;
    }




}


