package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * StudentDetails generated by hbm2java
 */
@Entity
@Table(name="student_details"
    ,catalog="e2rp"
)
public class StudentDetails  implements java.io.Serializable {


     private Integer seriId;
     private int studentSlId;
     private String class_;
     private String section;
     private String stream;
     private String roll;
     private int academicyear;
     private String flag1;
     private String flag2;
     private String flag3;
     private String flag4;
     private String flag5;
     private String studentIsactive;

    public StudentDetails() {
    }

	
    public StudentDetails(int studentSlId, String class_, String section, String stream, String roll, int academicyear, String studentIsactive) {
        this.studentSlId = studentSlId;
        this.class_ = class_;
        this.section = section;
        this.stream = stream;
        this.roll = roll;
        this.academicyear = academicyear;
        this.studentIsactive = studentIsactive;
    }
    public StudentDetails(int studentSlId, String class_, String section, String stream, String roll, int academicyear, String flag1, String flag2, String flag3, String flag4, String flag5, String studentIsactive) {
       this.studentSlId = studentSlId;
       this.class_ = class_;
       this.section = section;
       this.stream = stream;
       this.roll = roll;
       this.academicyear = academicyear;
       this.flag1 = flag1;
       this.flag2 = flag2;
       this.flag3 = flag3;
       this.flag4 = flag4;
       this.flag5 = flag5;
       this.studentIsactive = studentIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SERI_ID", unique=true, nullable=false)
    public Integer getSeriId() {
        return this.seriId;
    }
    
    public void setSeriId(Integer seriId) {
        this.seriId = seriId;
    }

    
    @Column(name="STUDENT_SL_ID", nullable=false)
    public int getStudentSlId() {
        return this.studentSlId;
    }
    
    public void setStudentSlId(int studentSlId) {
        this.studentSlId = studentSlId;
    }

    
    @Column(name="CLASS", nullable=false, length=30)
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }

    
    @Column(name="SECTION", nullable=false, length=10)
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }

    
    @Column(name="STREAM", nullable=false, length=30)
    public String getStream() {
        return this.stream;
    }
    
    public void setStream(String stream) {
        this.stream = stream;
    }

    
    @Column(name="ROLL", nullable=false, length=30)
    public String getRoll() {
        return this.roll;
    }
    
    public void setRoll(String roll) {
        this.roll = roll;
    }

    
    @Column(name="ACADEMICYEAR", nullable=false)
    public int getAcademicyear() {
        return this.academicyear;
    }
    
    public void setAcademicyear(int academicyear) {
        this.academicyear = academicyear;
    }

    
    @Column(name="FLAG_1", length=30)
    public String getFlag1() {
        return this.flag1;
    }
    
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    
    @Column(name="FLAG_2", length=30)
    public String getFlag2() {
        return this.flag2;
    }
    
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    
    @Column(name="FLAG_3", length=30)
    public String getFlag3() {
        return this.flag3;
    }
    
    public void setFlag3(String flag3) {
        this.flag3 = flag3;
    }

    
    @Column(name="FLAG_4", length=30)
    public String getFlag4() {
        return this.flag4;
    }
    
    public void setFlag4(String flag4) {
        this.flag4 = flag4;
    }

    
    @Column(name="FLAG_5", length=30)
    public String getFlag5() {
        return this.flag5;
    }
    
    public void setFlag5(String flag5) {
        this.flag5 = flag5;
    }

    
    @Column(name="STUDENT_ISACTIVE", nullable=false, length=30)
    public String getStudentIsactive() {
        return this.studentIsactive;
    }
    
    public void setStudentIsactive(String studentIsactive) {
        this.studentIsactive = studentIsactive;
    }




}


