package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StudentFeesDetails generated by hbm2java
 */
@Entity
@Table(name="student_fees_details"
    ,catalog="e2rp"
)
public class StudentFeesDetails  implements java.io.Serializable {


     private Integer studentFeesDetailsid;
     private int studentId;
     private String paymentMode;
     private BigDecimal paymentAmount;
     private String dueDate;
     private int paymentOption;
     private String chequeNo;
     private String chequeDate;
     private BigDecimal dueAmount;
     private Integer createdBy;
     private Date createdOn;
     private String feesIsactive;

    public StudentFeesDetails() {
    }

	
    public StudentFeesDetails(int studentId, String paymentMode, BigDecimal paymentAmount, String dueDate, int paymentOption, Date createdOn, String feesIsactive) {
        this.studentId = studentId;
        this.paymentMode = paymentMode;
        this.paymentAmount = paymentAmount;
        this.dueDate = dueDate;
        this.paymentOption = paymentOption;
        this.createdOn = createdOn;
        this.feesIsactive = feesIsactive;
    }
    public StudentFeesDetails(int studentId, String paymentMode, BigDecimal paymentAmount, String dueDate, int paymentOption, String chequeNo, String chequeDate, BigDecimal dueAmount, Integer createdBy, Date createdOn, String feesIsactive) {
       this.studentId = studentId;
       this.paymentMode = paymentMode;
       this.paymentAmount = paymentAmount;
       this.dueDate = dueDate;
       this.paymentOption = paymentOption;
       this.chequeNo = chequeNo;
       this.chequeDate = chequeDate;
       this.dueAmount = dueAmount;
       this.createdBy = createdBy;
       this.createdOn = createdOn;
       this.feesIsactive = feesIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="STUDENT_FEES_DETAILSID", unique=true, nullable=false)
    public Integer getStudentFeesDetailsid() {
        return this.studentFeesDetailsid;
    }
    
    public void setStudentFeesDetailsid(Integer studentFeesDetailsid) {
        this.studentFeesDetailsid = studentFeesDetailsid;
    }

    
    @Column(name="STUDENT_ID", nullable=false)
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }

    
    @Column(name="PAYMENT_MODE", nullable=false, length=10)
    public String getPaymentMode() {
        return this.paymentMode;
    }
    
    public void setPaymentMode(String paymentMode) {
        this.paymentMode = paymentMode;
    }

    
    @Column(name="PAYMENT_AMOUNT", nullable=false, precision=18)
    public BigDecimal getPaymentAmount() {
        return this.paymentAmount;
    }
    
    public void setPaymentAmount(BigDecimal paymentAmount) {
        this.paymentAmount = paymentAmount;
    }

    
    @Column(name="DUE_DATE", nullable=false, length=10)
    public String getDueDate() {
        return this.dueDate;
    }
    
    public void setDueDate(String dueDate) {
        this.dueDate = dueDate;
    }

    
    @Column(name="PAYMENT_OPTION", nullable=false)
    public int getPaymentOption() {
        return this.paymentOption;
    }
    
    public void setPaymentOption(int paymentOption) {
        this.paymentOption = paymentOption;
    }

    
    @Column(name="CHEQUE_NO", length=10)
    public String getChequeNo() {
        return this.chequeNo;
    }
    
    public void setChequeNo(String chequeNo) {
        this.chequeNo = chequeNo;
    }

    
    @Column(name="CHEQUE_DATE", length=10)
    public String getChequeDate() {
        return this.chequeDate;
    }
    
    public void setChequeDate(String chequeDate) {
        this.chequeDate = chequeDate;
    }

    
    @Column(name="DUE_AMOUNT", precision=18)
    public BigDecimal getDueAmount() {
        return this.dueAmount;
    }
    
    public void setDueAmount(BigDecimal dueAmount) {
        this.dueAmount = dueAmount;
    }

    
    @Column(name="CREATED_BY")
    public Integer getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_ON", nullable=false, length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="FEES_ISACTIVE", nullable=false, length=10)
    public String getFeesIsactive() {
        return this.feesIsactive;
    }
    
    public void setFeesIsactive(String feesIsactive) {
        this.feesIsactive = feesIsactive;
    }




}


