package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subjectmaster generated by hbm2java
 */
@Entity
@Table(name="subjectmaster"
    ,catalog="e2rp"
)
public class Subjectmaster  implements java.io.Serializable {


     private Integer sid;
     private int cid;
     private int subjectId;
     private String subjectName;

    public Subjectmaster() {
    }

    public Subjectmaster(int cid, int subjectId, String subjectName) {
       this.cid = cid;
       this.subjectId = subjectId;
       this.subjectName = subjectName;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SID", unique=true, nullable=false)
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    
    @Column(name="CID", nullable=false)
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }

    
    @Column(name="SUBJECT_ID", nullable=false)
    public int getSubjectId() {
        return this.subjectId;
    }
    
    public void setSubjectId(int subjectId) {
        this.subjectId = subjectId;
    }

    
    @Column(name="SUBJECT_NAME", nullable=false, length=20)
    public String getSubjectName() {
        return this.subjectName;
    }
    
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }




}


