package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supplier generated by hbm2java
 */
@Entity
@Table(name="supplier"
    ,catalog="e2rp"
)
public class Supplier  implements java.io.Serializable {


     private Integer suppId;
     private String suppCode;
     private String suppName;
     private String suppAddress;
     private String suppPhone;
     private String suppType;
     private int suppCreatedby;
     private Date suppCreateddt;
     private String suppIsactive;

    public Supplier() {
    }

    public Supplier(String suppCode, String suppName, String suppAddress, String suppPhone, String suppType, int suppCreatedby, Date suppCreateddt, String suppIsactive) {
       this.suppCode = suppCode;
       this.suppName = suppName;
       this.suppAddress = suppAddress;
       this.suppPhone = suppPhone;
       this.suppType = suppType;
       this.suppCreatedby = suppCreatedby;
       this.suppCreateddt = suppCreateddt;
       this.suppIsactive = suppIsactive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SUPP_ID", unique=true, nullable=false)
    public Integer getSuppId() {
        return this.suppId;
    }
    
    public void setSuppId(Integer suppId) {
        this.suppId = suppId;
    }

    
    @Column(name="SUPP_CODE", nullable=false, length=20)
    public String getSuppCode() {
        return this.suppCode;
    }
    
    public void setSuppCode(String suppCode) {
        this.suppCode = suppCode;
    }

    
    @Column(name="SUPP_NAME", nullable=false, length=100)
    public String getSuppName() {
        return this.suppName;
    }
    
    public void setSuppName(String suppName) {
        this.suppName = suppName;
    }

    
    @Column(name="SUPP_ADDRESS", nullable=false)
    public String getSuppAddress() {
        return this.suppAddress;
    }
    
    public void setSuppAddress(String suppAddress) {
        this.suppAddress = suppAddress;
    }

    
    @Column(name="SUPP_PHONE", nullable=false, length=50)
    public String getSuppPhone() {
        return this.suppPhone;
    }
    
    public void setSuppPhone(String suppPhone) {
        this.suppPhone = suppPhone;
    }

    
    @Column(name="SUPP_TYPE", nullable=false, length=50)
    public String getSuppType() {
        return this.suppType;
    }
    
    public void setSuppType(String suppType) {
        this.suppType = suppType;
    }

    
    @Column(name="SUPP_CREATEDBY", nullable=false)
    public int getSuppCreatedby() {
        return this.suppCreatedby;
    }
    
    public void setSuppCreatedby(int suppCreatedby) {
        this.suppCreatedby = suppCreatedby;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="SUPP_CREATEDDT", nullable=false, length=19)
    public Date getSuppCreateddt() {
        return this.suppCreateddt;
    }
    
    public void setSuppCreateddt(Date suppCreateddt) {
        this.suppCreateddt = suppCreateddt;
    }

    
    @Column(name="SUPP_ISACTIVE", nullable=false, length=1)
    public String getSuppIsactive() {
        return this.suppIsactive;
    }
    
    public void setSuppIsactive(String suppIsactive) {
        this.suppIsactive = suppIsactive;
    }




}


