package com.model.pojo;
// Generated 15 Apr, 2015 12:30:14 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TcodeMaster generated by hbm2java
 */
@Entity
@Table(name="tcode master"
    ,catalog="e2rp"
)
public class TcodeMaster  implements java.io.Serializable {


     private Integer id;
     private String tcode;
     private String desc;

    public TcodeMaster() {
    }

	
    public TcodeMaster(String tcode) {
        this.tcode = tcode;
    }
    public TcodeMaster(String tcode, String desc) {
       this.tcode = tcode;
       this.desc = desc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Tcode", nullable=false, length=50)
    public String getTcode() {
        return this.tcode;
    }
    
    public void setTcode(String tcode) {
        this.tcode = tcode;
    }

    
    @Column(name="DESC")
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


