package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Typeofcode generated by hbm2java
 */
@Entity
@Table(name="typeofcode"
    ,catalog="e2rp"
)
public class Typeofcode  implements java.io.Serializable {


     private Integer tocId;
     private String tocPrefix;
     private String tocDescr;
     private String tocSeparator;
     private int tocSuffixlen;
     private int tocTocmasid;
     private String tocIseditable;
     private String tocIsauto;
     private String tocIsdiscont;
     private Date tocCreationdt;

    public Typeofcode() {
    }

    public Typeofcode(String tocPrefix, String tocDescr, String tocSeparator, int tocSuffixlen, int tocTocmasid, String tocIseditable, String tocIsauto, String tocIsdiscont, Date tocCreationdt) {
       this.tocPrefix = tocPrefix;
       this.tocDescr = tocDescr;
       this.tocSeparator = tocSeparator;
       this.tocSuffixlen = tocSuffixlen;
       this.tocTocmasid = tocTocmasid;
       this.tocIseditable = tocIseditable;
       this.tocIsauto = tocIsauto;
       this.tocIsdiscont = tocIsdiscont;
       this.tocCreationdt = tocCreationdt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TOC_ID", unique=true, nullable=false)
    public Integer getTocId() {
        return this.tocId;
    }
    
    public void setTocId(Integer tocId) {
        this.tocId = tocId;
    }

    
    @Column(name="TOC_PREFIX", nullable=false, length=8)
    public String getTocPrefix() {
        return this.tocPrefix;
    }
    
    public void setTocPrefix(String tocPrefix) {
        this.tocPrefix = tocPrefix;
    }

    
    @Column(name="TOC_DESCR", nullable=false, length=50)
    public String getTocDescr() {
        return this.tocDescr;
    }
    
    public void setTocDescr(String tocDescr) {
        this.tocDescr = tocDescr;
    }

    
    @Column(name="TOC_SEPARATOR", nullable=false, length=1)
    public String getTocSeparator() {
        return this.tocSeparator;
    }
    
    public void setTocSeparator(String tocSeparator) {
        this.tocSeparator = tocSeparator;
    }

    
    @Column(name="TOC_SUFFIXLEN", nullable=false)
    public int getTocSuffixlen() {
        return this.tocSuffixlen;
    }
    
    public void setTocSuffixlen(int tocSuffixlen) {
        this.tocSuffixlen = tocSuffixlen;
    }

    
    @Column(name="TOC_TOCMASID", nullable=false)
    public int getTocTocmasid() {
        return this.tocTocmasid;
    }
    
    public void setTocTocmasid(int tocTocmasid) {
        this.tocTocmasid = tocTocmasid;
    }

    
    @Column(name="TOC_ISEDITABLE", nullable=false, length=8)
    public String getTocIseditable() {
        return this.tocIseditable;
    }
    
    public void setTocIseditable(String tocIseditable) {
        this.tocIseditable = tocIseditable;
    }

    
    @Column(name="TOC_ISAUTO", nullable=false, length=8)
    public String getTocIsauto() {
        return this.tocIsauto;
    }
    
    public void setTocIsauto(String tocIsauto) {
        this.tocIsauto = tocIsauto;
    }

    
    @Column(name="TOC_ISDISCONT", nullable=false, length=8)
    public String getTocIsdiscont() {
        return this.tocIsdiscont;
    }
    
    public void setTocIsdiscont(String tocIsdiscont) {
        this.tocIsdiscont = tocIsdiscont;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="TOC_CREATIONDT", nullable=false, length=19)
    public Date getTocCreationdt() {
        return this.tocCreationdt;
    }
    
    public void setTocCreationdt(Date tocCreationdt) {
        this.tocCreationdt = tocCreationdt;
    }




}


