package com.model.pojo;
// Generated 13 Apr, 2015 11:03:03 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkorderDetails generated by hbm2java
 */
@Entity
@Table(name="workorder_details"
    ,catalog="e2rp"
)
public class WorkorderDetails  implements java.io.Serializable {


     private Integer wodtlsId;
     private String orderNo;
     private int itemId;
     private String jobdetls;
     private BigDecimal quantity;
     private String unit;
     private String rate;
     private BigDecimal totalvalue;
     private String descriptions;
     private int createdBy;
     private Date createdDt;
     private String suppName;
     private String suppPhone;

    public WorkorderDetails() {
    }

    public WorkorderDetails(String orderNo, int itemId, String jobdetls, BigDecimal quantity, String unit, String rate, BigDecimal totalvalue, String descriptions, int createdBy, Date createdDt, String suppName, String suppPhone) {
       this.orderNo = orderNo;
       this.itemId = itemId;
       this.jobdetls = jobdetls;
       this.quantity = quantity;
       this.unit = unit;
       this.rate = rate;
       this.totalvalue = totalvalue;
       this.descriptions = descriptions;
       this.createdBy = createdBy;
       this.createdDt = createdDt;
       this.suppName = suppName;
       this.suppPhone = suppPhone;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="WODTLS_ID", unique=true, nullable=false)
    public Integer getWodtlsId() {
        return this.wodtlsId;
    }
    
    public void setWodtlsId(Integer wodtlsId) {
        this.wodtlsId = wodtlsId;
    }

    
    @Column(name="ORDER_NO", nullable=false, length=20)
    public String getOrderNo() {
        return this.orderNo;
    }
    
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    
    @Column(name="ITEM_ID", nullable=false)
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }

    
    @Column(name="JOBDETLS", nullable=false, length=100)
    public String getJobdetls() {
        return this.jobdetls;
    }
    
    public void setJobdetls(String jobdetls) {
        this.jobdetls = jobdetls;
    }

    
    @Column(name="QUANTITY", nullable=false, precision=18)
    public BigDecimal getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="UNIT", nullable=false, length=50)
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }

    
    @Column(name="RATE", nullable=false, length=50)
    public String getRate() {
        return this.rate;
    }
    
    public void setRate(String rate) {
        this.rate = rate;
    }

    
    @Column(name="TOTALVALUE", nullable=false, precision=18)
    public BigDecimal getTotalvalue() {
        return this.totalvalue;
    }
    
    public void setTotalvalue(BigDecimal totalvalue) {
        this.totalvalue = totalvalue;
    }

    
    @Column(name="DESCRIPTIONS", nullable=false, length=100)
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }

    
    @Column(name="CREATED_BY", nullable=false)
    public int getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DT", nullable=false, length=19)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    
    @Column(name="SUPP_NAME", nullable=false, length=50)
    public String getSuppName() {
        return this.suppName;
    }
    
    public void setSuppName(String suppName) {
        this.suppName = suppName;
    }

    
    @Column(name="SUPP_PHONE", nullable=false, length=50)
    public String getSuppPhone() {
        return this.suppPhone;
    }
    
    public void setSuppPhone(String suppPhone) {
        this.suppPhone = suppPhone;
    }




}


